<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JayTom.Dws.Camera\JayTom.Dws.Camera.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="WindowsFormsIntegration">
      <HintPath>C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\7.0.14\ref\net7.0\WindowsFormsIntegration.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
