<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\Font\demo.css" />
    <Content Remove="wwwroot\Font\demo_index.html" />
    <Content Remove="wwwroot\Font\iconfont.css" />
    <Content Remove="wwwroot\Font\iconfont.js" />
    <Content Remove="wwwroot\Font\iconfont.ttf" />
    <Content Remove="wwwroot\Font\iconfont.woff" />
    <Content Remove="wwwroot\Font\iconfont.woff2" />
    <Content Remove="wwwroot\Images\defaultImage.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" Version="6.12.0" />
    <PackageReference Include="MudBlazor.ThemeManager" Version="1.0.8" />
    <PackageReference Include="System.Drawing.Common" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\Font\demo.css" />
    <None Include="wwwroot\Font\demo_index.html" />
    <None Include="wwwroot\Font\iconfont.css" />
    <None Include="wwwroot\Font\iconfont.js" />
    <None Include="wwwroot\Font\iconfont.ttf" />
    <None Include="wwwroot\Font\iconfont.woff" />
    <None Include="wwwroot\Font\iconfont.woff2" />
    <None Include="wwwroot\Images\defaultImage.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
