//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JayTom.Dws.Client.Languages {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JayTom.Dws.Client.Languages.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 3D相机/体积相机 的本地化字符串。
        /// </summary>
        public static string _3DCamera_VolumeCamera {
            get {
                return ResourceManager.GetString("3DCamera/VolumeCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加音频: 的本地化字符串。
        /// </summary>
        public static string AddAudio {
            get {
                return ResourceManager.GetString("AddAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 附加内容 的本地化字符串。
        /// </summary>
        public static string AdditionalContent {
            get {
                return ResourceManager.GetString("AdditionalContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 附加重量属性: 的本地化字符串。
        /// </summary>
        public static string AdditionalWeightAttributes {
            get {
                return ResourceManager.GetString("AdditionalWeightAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包裹出发后 的本地化字符串。
        /// </summary>
        public static string AfterPackageDeparture {
            get {
                return ResourceManager.GetString("AfterPackageDeparture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置输出后 的本地化字符串。
        /// </summary>
        public static string AfterPositionOutput {
            get {
                return ResourceManager.GetString("AfterPositionOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扫码结束后 的本地化字符串。
        /// </summary>
        public static string AfterScanning {
            get {
                return ResourceManager.GetString("AfterScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口输出后 的本地化字符串。
        /// </summary>
        public static string AfterSerialPortOutput {
            get {
                return ResourceManager.GetString("AfterSerialPortOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tcp输出后 的本地化字符串。
        /// </summary>
        public static string AfterTCPOutput {
            get {
                return ResourceManager.GetString("AfterTCPOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 称重结束后 的本地化字符串。
        /// </summary>
        public static string AfterWeighing {
            get {
                return ResourceManager.GetString("AfterWeighing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        public static string ApiFailure {
            get {
                return ResourceManager.GetString("ApiFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Api接口 的本地化字符串。
        /// </summary>
        public static string ApiInterface {
            get {
                return ResourceManager.GetString("ApiInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Api接口响应 的本地化字符串。
        /// </summary>
        public static string APIInterfaceResponse {
            get {
                return ResourceManager.GetString("APIInterfaceResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未上传 的本地化字符串。
        /// </summary>
        public static string ApiNotUploaded {
            get {
                return ResourceManager.GetString("ApiNotUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传状态: 的本地化字符串。
        /// </summary>
        public static string APIResponseStatus {
            get {
                return ResourceManager.GetString("APIResponseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        public static string ApiSuccess {
            get {
                return ResourceManager.GetString("ApiSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Api上传接口设置 的本地化字符串。
        /// </summary>
        public static string Api上传接口设置 {
            get {
                return ResourceManager.GetString("Api上传接口设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用全部 的本地化字符串。
        /// </summary>
        public static string ApplyAll {
            get {
                return ResourceManager.GetString("ApplyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动清理: 的本地化字符串。
        /// </summary>
        public static string AutomaticCleanup {
            get {
                return ResourceManager.GetString("AutomaticCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可用内存: 的本地化字符串。
        /// </summary>
        public static string AvailableMemory {
            get {
                return ResourceManager.GetString("AvailableMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MB空间(清理等级最高) 的本地化字符串。
        /// </summary>
        public static string AvailableSpace {
            get {
                return ResourceManager.GetString("AvailableSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包裹条码 的本地化字符串。
        /// </summary>
        public static string BarCode {
            get {
                return ResourceManager.GetString("BarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条码: 的本地化字符串。
        /// </summary>
        public static string BarcodeCondition {
            get {
                return ResourceManager.GetString("BarcodeCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 天之前的条码数据 的本地化字符串。
        /// </summary>
        public static string BarcodeDataDaysAgo {
            get {
                return ResourceManager.GetString("BarcodeDataDaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许条码间隔数量: 的本地化字符串。
        /// </summary>
        public static string BarcodeIntervalLimit {
            get {
                return ResourceManager.GetString("BarcodeIntervalLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条码长度: 的本地化字符串。
        /// </summary>
        public static string BarcodeLength {
            get {
                return ResourceManager.GetString("BarcodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条码坐标: 的本地化字符串。
        /// </summary>
        public static string BarcodePoints {
            get {
                return ResourceManager.GetString("BarcodePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条码验证: 的本地化字符串。
        /// </summary>
        public static string BarcodeValidation {
            get {
                return ResourceManager.GetString("BarcodeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 波特率: 的本地化字符串。
        /// </summary>
        public static string BaudRate {
            get {
                return ResourceManager.GetString("BaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绑定 的本地化字符串。
        /// </summary>
        public static string Bind {
            get {
                return ResourceManager.GetString("Bind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绑定到体积相机 的本地化字符串。
        /// </summary>
        public static string BindToCompactCamera {
            get {
                return ResourceManager.GetString("BindToCompactCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绑定到全景相机 的本地化字符串。
        /// </summary>
        public static string BindToPanoramicCamera {
            get {
                return ResourceManager.GetString("BindToPanoramicCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绑定到扫码相机 的本地化字符串。
        /// </summary>
        public static string BindToScannerCamera {
            get {
                return ResourceManager.GetString("BindToScannerCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 蓝牙连接 的本地化字符串。
        /// </summary>
        public static string BluetoothConnection {
            get {
                return ResourceManager.GetString("BluetoothConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左下角 的本地化字符串。
        /// </summary>
        public static string BottomLeftCorner {
            get {
                return ResourceManager.GetString("BottomLeftCorner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右下角 的本地化字符串。
        /// </summary>
        public static string BottomRightCorner {
            get {
                return ResourceManager.GetString("BottomRightCorner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览目录 的本地化字符串。
        /// </summary>
        public static string BrowseDirectory {
            get {
                return ResourceManager.GetString("BrowseDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空间清理 的本地化字符串。
        /// </summary>
        public static string CacheCearing {
            get {
                return ResourceManager.GetString("CacheCearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机 的本地化字符串。
        /// </summary>
        public static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机配置 的本地化字符串。
        /// </summary>
        public static string CameraConfiguration {
            get {
                return ResourceManager.GetString("CameraConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机查找 的本地化字符串。
        /// </summary>
        public static string CameraSearch {
            get {
                return ResourceManager.GetString("CameraSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能包含: 的本地化字符串。
        /// </summary>
        public static string CannotContain {
            get {
                return ResourceManager.GetString("CannotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符长度: 的本地化字符串。
        /// </summary>
        public static string CharacterLength {
            get {
                return ResourceManager.GetString("CharacterLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符限制: 的本地化字符串。
        /// </summary>
        public static string CharacterLimitation {
            get {
                return ResourceManager.GetString("CharacterLimitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空条件 的本地化字符串。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 体积相机 的本地化字符串。
        /// </summary>
        public static string CompactCamera {
            get {
                return ResourceManager.GetString("CompactCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完全匹配: 的本地化字符串。
        /// </summary>
        public static string CompleteMatch {
            get {
                return ResourceManager.GetString("CompleteMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多个条件请使用英文;号分割 的本地化字符串。
        /// </summary>
        public static string ConditionSeparationInstruction {
            get {
                return ResourceManager.GetString("ConditionSeparationInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包含字符串: 的本地化字符串。
        /// </summary>
        public static string ContainString {
            get {
                return ResourceManager.GetString("ContainString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容 的本地化字符串。
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包含的内容: 的本地化字符串。
        /// </summary>
        public static string ContentContained {
            get {
                return ResourceManager.GetString("ContentContained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容格式(Json) 的本地化字符串。
        /// </summary>
        public static string ContentFormat {
            get {
                return ResourceManager.GetString("ContentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cpu风扇转速: 的本地化字符串。
        /// </summary>
        public static string CpuFanSpeed {
            get {
                return ResourceManager.GetString("CpuFanSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cpu速度: 的本地化字符串。
        /// </summary>
        public static string CpuSpeed {
            get {
                return ResourceManager.GetString("CpuSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cpu温度: 的本地化字符串。
        /// </summary>
        public static string CpuTemperature {
            get {
                return ResourceManager.GetString("CpuTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cpu使用率: 的本地化字符串。
        /// </summary>
        public static string CpuUsageRate {
            get {
                return ResourceManager.GetString("CpuUsageRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义 的本地化字符串。
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据 的本地化字符串。
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据位: 的本地化字符串。
        /// </summary>
        public static string DataBits {
            get {
                return ResourceManager.GetString("DataBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格  式: 的本地化字符串。
        /// </summary>
        public static string DataFormat {
            get {
                return ResourceManager.GetString("DataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据管理 的本地化字符串。
        /// </summary>
        public static string DataManagement {
            get {
                return ResourceManager.GetString("DataManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取方式: 的本地化字符串。
        /// </summary>
        public static string DataRetrievalMode {
            get {
                return ResourceManager.GetString("DataRetrievalMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据模板: 的本地化字符串。
        /// </summary>
        public static string DataTemplate {
            get {
                return ResourceManager.GetString("DataTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期 的本地化字符串。
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小数保留位数: 的本地化字符串。
        /// </summary>
        public static string DecimalPlaces {
            get {
                return ResourceManager.GetString("DecimalPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认Api接口 的本地化字符串。
        /// </summary>
        public static string DefaultApi {
            get {
                return ResourceManager.GetString("DefaultApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 延迟触发时间(毫秒): 的本地化字符串。
        /// </summary>
        public static string DelayTriggerTime {
            get {
                return ResourceManager.GetString("DelayTriggerTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 磁盘空间: 的本地化字符串。
        /// </summary>
        public static string DiskSpace {
            get {
                return ResourceManager.GetString("DiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动态称重 的本地化字符串。
        /// </summary>
        public static string DynamicWeighing {
            get {
                return ResourceManager.GetString("DynamicWeighing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结尾字符: 的本地化字符串。
        /// </summary>
        public static string EndCharacter {
            get {
                return ResourceManager.GetString("EndCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小数结束位置: 的本地化字符串。
        /// </summary>
        public static string EndPositionOfDecimal {
            get {
                return ResourceManager.GetString("EndPositionOfDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 整数结束位置: 的本地化字符串。
        /// </summary>
        public static string EndPositionOfInteger {
            get {
                return ResourceManager.GetString("EndPositionOfInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网口连接 的本地化字符串。
        /// </summary>
        public static string EthernetConnection {
            get {
                return ResourceManager.GetString("EthernetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Excel文件 的本地化字符串。
        /// </summary>
        public static string Excel文件 {
            get {
                return ResourceManager.GetString("Excel文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常数量 的本地化字符串。
        /// </summary>
        public static string ExceptionCount {
            get {
                return ResourceManager.GetString("ExceptionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        public static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败音频: 的本地化字符串。
        /// </summary>
        public static string FailureAudio {
            get {
                return ResourceManager.GetString("FailureAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过滤设置 的本地化字符串。
        /// </summary>
        public static string FilteringSettings {
            get {
                return ResourceManager.GetString("FilteringSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        public static string FirstPage {
            get {
                return ResourceManager.GetString("FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 天之前的FTP图片  的本地化字符串。
        /// </summary>
        public static string FTPImageDaysAgo {
            get {
                return ResourceManager.GetString("FTPImageDaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FTP空间: 的本地化字符串。
        /// </summary>
        public static string FTPSpace {
            get {
                return ResourceManager.GetString("FTPSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FTP上传: 的本地化字符串。
        /// </summary>
        public static string FTPUpload {
            get {
                return ResourceManager.GetString("FTPUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gpu使用率: 的本地化字符串。
        /// </summary>
        public static string GpuUsageRate {
            get {
                return ResourceManager.GetString("GpuUsageRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 硬盘 的本地化字符串。
        /// </summary>
        public static string HardDisk {
            get {
                return ResourceManager.GetString("HardDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高度: 的本地化字符串。
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小时 的本地化字符串。
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标 识 符: 的本地化字符串。
        /// </summary>
        public static string Identifier {
            get {
                return ResourceManager.GetString("Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标识符位置: 的本地化字符串。
        /// </summary>
        public static string IdentifierPosition {
            get {
                return ResourceManager.GetString("IdentifierPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片名 的本地化字符串。
        /// </summary>
        public static string ImageName {
            get {
                return ResourceManager.GetString("ImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片命名: 的本地化字符串。
        /// </summary>
        public static string ImageNaming {
            get {
                return ResourceManager.GetString("ImageNaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存图根目录: 的本地化字符串。
        /// </summary>
        public static string ImageRootDirectory {
            get {
                return ResourceManager.GetString("ImageRootDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存图设置 的本地化字符串。
        /// </summary>
        public static string ImageStorageSettings {
            get {
                return ResourceManager.GetString("ImageStorageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存图类型: 的本地化字符串。
        /// </summary>
        public static string ImageType {
            get {
                return ResourceManager.GetString("ImageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工业相机 的本地化字符串。
        /// </summary>
        public static string IndustrialCamera {
            get {
                return ResourceManager.GetString("IndustrialCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容输入 的本地化字符串。
        /// </summary>
        public static string InputContent {
            get {
                return ResourceManager.GetString("InputContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入数据: 的本地化字符串。
        /// </summary>
        public static string InputData {
            get {
                return ResourceManager.GetString("InputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入模板: 的本地化字符串。
        /// </summary>
        public static string InputTemplate {
            get {
                return ResourceManager.GetString("InputTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接口参数: 的本地化字符串。
        /// </summary>
        public static string InterfaceParameters {
            get {
                return ResourceManager.GetString("InterfaceParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP地址: 的本地化字符串。
        /// </summary>
        public static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否开启实时图像: 的本地化字符串。
        /// </summary>
        public static string IsEnableRealTimeImage {
            get {
                return ResourceManager.GetString("IsEnableRealTimeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否输出条码 的本地化字符串。
        /// </summary>
        public static string IsOutputBarcode {
            get {
                return ResourceManager.GetString("IsOutputBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否输出重量: 的本地化字符串。
        /// </summary>
        public static string IsOutputWeight {
            get {
                return ResourceManager.GetString("IsOutputWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否优先输出重量: 的本地化字符串。
        /// </summary>
        public static string IsPrioritizeWeightOutput {
            get {
                return ResourceManager.GetString("IsPrioritizeWeightOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序重启重新上传未成功数据: 的本地化字符串。
        /// </summary>
        public static string IsRetryOutput {
            get {
                return ResourceManager.GetString("IsRetryOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否反转: 的本地化字符串。
        /// </summary>
        public static string IsReverse {
            get {
                return ResourceManager.GetString("IsReverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否使用实际重量转换率: 的本地化字符串。
        /// </summary>
        public static string IsUseActualWeightConversionRate {
            get {
                return ResourceManager.GetString("IsUseActualWeightConversionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否使用追加重量: 的本地化字符串。
        /// </summary>
        public static string IsUseAdditionalWeight {
            get {
                return ResourceManager.GetString("IsUseAdditionalWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用音频输出: 的本地化字符串。
        /// </summary>
        public static string IsUseAudioOutput {
            get {
                return ResourceManager.GetString("IsUseAudioOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否使用控件输入 的本地化字符串。
        /// </summary>
        public static string IsUseControlInput {
            get {
                return ResourceManager.GetString("IsUseControlInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否使用固定重量: 的本地化字符串。
        /// </summary>
        public static string IsUseFixedWeight {
            get {
                return ResourceManager.GetString("IsUseFixedWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否使用FTP上传: 的本地化字符串。
        /// </summary>
        public static string IsUseFTPUpload {
            get {
                return ResourceManager.GetString("IsUseFTPUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否使用融合重量超时: 的本地化字符串。
        /// </summary>
        public static string IsUseFusedWeightTimeout {
            get {
                return ResourceManager.GetString("IsUseFusedWeightTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否使用Json格式: 的本地化字符串。
        /// </summary>
        public static string IsUseJSONFormat {
            get {
                return ResourceManager.GetString("IsUseJSONFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用位置输出 的本地化字符串。
        /// </summary>
        public static string IsUsePositionOutput {
            get {
                return ResourceManager.GetString("IsUsePositionOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否使用原图: 的本地化字符串。
        /// </summary>
        public static string IsUserOriginalImage {
            get {
                return ResourceManager.GetString("IsUserOriginalImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否使用串口输入: 的本地化字符串。
        /// </summary>
        public static string IsUseSerialInput {
            get {
                return ResourceManager.GetString("IsUseSerialInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用串口输出: 的本地化字符串。
        /// </summary>
        public static string IsUseSerialPortOutput {
            get {
                return ResourceManager.GetString("IsUseSerialPortOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用TCP客户端 的本地化字符串。
        /// </summary>
        public static string IsUseTCPClient {
            get {
                return ResourceManager.GetString("IsUseTCPClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否使用TCP输入: 的本地化字符串。
        /// </summary>
        public static string IsUseTCPInput {
            get {
                return ResourceManager.GetString("IsUseTCPInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用TCP输出: 的本地化字符串。
        /// </summary>
        public static string IsUseTCPOutput {
            get {
                return ResourceManager.GetString("IsUseTCPOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用TCP服务端 的本地化字符串。
        /// </summary>
        public static string IsUseTCPServer {
            get {
                return ResourceManager.GetString("IsUseTCPServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否使用水印: 的本地化字符串。
        /// </summary>
        public static string IsUseWatermark {
            get {
                return ResourceManager.GetString("IsUseWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出条码后按键: 的本地化字符串。
        /// </summary>
        public static string KeyPressAfterOutputtingBarcode {
            get {
                return ResourceManager.GetString("KeyPressAfterOutputtingBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出重量后按键: 的本地化字符串。
        /// </summary>
        public static string KeyPressAfterOutputtingWeight {
            get {
                return ResourceManager.GetString("KeyPressAfterOutputtingWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 末页 的本地化字符串。
        /// </summary>
        public static string LastPage {
            get {
                return ResourceManager.GetString("LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 长度: 的本地化字符串。
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字母 的本地化字符串。
        /// </summary>
        public static string Letters {
            get {
                return ResourceManager.GetString("Letters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字母或数字 的本地化字符串。
        /// </summary>
        public static string LettersOrNumbers {
            get {
                return ResourceManager.GetString("LettersOrNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载图片 的本地化字符串。
        /// </summary>
        public static string LoadImage {
            get {
                return ResourceManager.GetString("LoadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 天之前的日志图片 的本地化字符串。
        /// </summary>
        public static string LogDataDaysAgo {
            get {
                return ResourceManager.GetString("LogDataDaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志信息 的本地化字符串。
        /// </summary>
        public static string LogInformation {
            get {
                return ResourceManager.GetString("LogInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志管理 的本地化字符串。
        /// </summary>
        public static string LogManagement {
            get {
                return ResourceManager.GetString("LogManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动清理: 的本地化字符串。
        /// </summary>
        public static string ManualCleanup {
            get {
                return ResourceManager.GetString("ManualCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大条码位数: 的本地化字符串。
        /// </summary>
        public static string MaxBarcodeLength {
            get {
                return ResourceManager.GetString("MaxBarcodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大测量长度: 的本地化字符串。
        /// </summary>
        public static string MaximumLength {
            get {
                return ResourceManager.GetString("MaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大同步时间: 的本地化字符串。
        /// </summary>
        public static string MaximumSynchronizationTime {
            get {
                return ResourceManager.GetString("MaximumSynchronizationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大可用重量: 的本地化字符串。
        /// </summary>
        public static string MaxUsableWeight {
            get {
                return ResourceManager.GetString("MaxUsableWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 体积测量模式: 的本地化字符串。
        /// </summary>
        public static string MeasurementMode {
            get {
                return ResourceManager.GetString("MeasurementMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内存 的本地化字符串。
        /// </summary>
        public static string MemoryInformation {
            get {
                return ResourceManager.GetString("MemoryInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内存使用率: 的本地化字符串。
        /// </summary>
        public static string MemoryUsageRate {
            get {
                return ResourceManager.GetString("MemoryUsageRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 磁盘最小可用空间保障 的本地化字符串。
        /// </summary>
        public static string MinAvailable {
            get {
                return ResourceManager.GetString("MinAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小条码位数: 的本地化字符串。
        /// </summary>
        public static string MinBarcodeLength {
            get {
                return ResourceManager.GetString("MinBarcodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小测量长度: 的本地化字符串。
        /// </summary>
        public static string MinimumLength {
            get {
                return ResourceManager.GetString("MinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 磁盘最少保留 的本地化字符串。
        /// </summary>
        public static string MinimumRetention {
            get {
                return ResourceManager.GetString("MinimumRetention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小同步时间： 的本地化字符串。
        /// </summary>
        public static string MinimumSynchronizationTime {
            get {
                return ResourceManager.GetString("MinimumSynchronizationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小可用重量: 的本地化字符串。
        /// </summary>
        public static string MinUsableWeight {
            get {
                return ResourceManager.GetString("MinUsableWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月份 的本地化字符串。
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须包含: 的本地化字符串。
        /// </summary>
        public static string MustContain {
            get {
                return ResourceManager.GetString("MustContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命名包含: 的本地化字符串。
        /// </summary>
        public static string NamingIncludes {
            get {
                return ResourceManager.GetString("NamingIncludes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络信息 的本地化字符串。
        /// </summary>
        public static string NetworkInformation {
            get {
                return ResourceManager.GetString("NetworkInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未连接 的本地化字符串。
        /// </summary>
        public static string NetworkNotConnected {
            get {
                return ResourceManager.GetString("NetworkNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 速度: 的本地化字符串。
        /// </summary>
        public static string NetworkSpeed {
            get {
                return ResourceManager.GetString("NetworkSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一页 的本地化字符串。
        /// </summary>
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有数据 的本地化字符串。
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非程序占用 的本地化字符串。
        /// </summary>
        public static string Non_ProgramUsage {
            get {
                return ResourceManager.GetString("Non-ProgramUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不使用接口 的本地化字符串。
        /// </summary>
        public static string NoneApi {
            get {
                return ResourceManager.GetString("NoneApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不称重 的本地化字符串。
        /// </summary>
        public static string NoWeighing {
            get {
                return ResourceManager.GetString("NoWeighing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数字 的本地化字符串。
        /// </summary>
        public static string Numbers {
            get {
                return ResourceManager.GetString("Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出配置: 的本地化字符串。
        /// </summary>
        public static string OutputConfiguration {
            get {
                return ResourceManager.GetString("OutputConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出数据: 的本地化字符串。
        /// </summary>
        public static string OutputData {
            get {
                return ResourceManager.GetString("OutputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作延时: 的本地化字符串。
        /// </summary>
        public static string OutputDelay {
            get {
                return ResourceManager.GetString("OutputDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结果输出 的本地化字符串。
        /// </summary>
        public static string OutputResults {
            get {
                return ResourceManager.GetString("OutputResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包裹识别 的本地化字符串。
        /// </summary>
        public static string PackgeRecognition {
            get {
                return ResourceManager.GetString("PackgeRecognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 补位变量 的本地化字符串。
        /// </summary>
        public static string PaddingVariable {
            get {
                return ResourceManager.GetString("PaddingVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全景相机 的本地化字符串。
        /// </summary>
        public static string PanoramicCamera {
            get {
                return ResourceManager.GetString("PanoramicCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全景图 的本地化字符串。
        /// </summary>
        public static string PanoramicImage {
            get {
                return ResourceManager.GetString("PanoramicImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 天之前的全景图片 的本地化字符串。
        /// </summary>
        public static string PanoramicImageDaysAgo {
            get {
                return ResourceManager.GetString("PanoramicImageDaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全景图片 的本地化字符串。
        /// </summary>
        public static string PanoramicImages {
            get {
                return ResourceManager.GetString("PanoramicImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 效验位: 的本地化字符串。
        /// </summary>
        public static string ParityBit {
            get {
                return ResourceManager.GetString("ParityBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码: 的本地化字符串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口: 的本地化字符串。
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一页 的本地化字符串。
        /// </summary>
        public static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只读式 的本地化字符串。
        /// </summary>
        public static string ReadOnly {
            get {
                return ResourceManager.GetString("ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实时重量数据: 的本地化字符串。
        /// </summary>
        public static string RealTimeWeightData {
            get {
                return ResourceManager.GetString("RealTimeWeightData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正则表达式: 的本地化字符串。
        /// </summary>
        public static string RegularExpression {
            get {
                return ResourceManager.GetString("RegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正则匹配: 的本地化字符串。
        /// </summary>
        public static string RegularMatching {
            get {
                return ResourceManager.GetString("RegularMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 问答式 的本地化字符串。
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求内容: 的本地化字符串。
        /// </summary>
        public static string RequestContent {
            get {
                return ResourceManager.GetString("RequestContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送内容: 的本地化字符串。
        /// </summary>
        public static string RequestedOfContent {
            get {
                return ResourceManager.GetString("RequestedOfContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送格式: 的本地化字符串。
        /// </summary>
        public static string RequestedOfFormat {
            get {
                return ResourceManager.GetString("RequestedOfFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求时间: 的本地化字符串。
        /// </summary>
        public static string RequestTime {
            get {
                return ResourceManager.GetString("RequestTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求超时时间: 的本地化字符串。
        /// </summary>
        public static string RequestTimeout {
            get {
                return ResourceManager.GetString("RequestTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 响应的内容: 的本地化字符串。
        /// </summary>
        public static string ResponseContent {
            get {
                return ResourceManager.GetString("ResponseContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 响应时间: 的本地化字符串。
        /// </summary>
        public static string ResponseTime {
            get {
                return ResourceManager.GetString("ResponseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结果判断 的本地化字符串。
        /// </summary>
        public static string ResultEvaluation {
            get {
                return ResourceManager.GetString("ResultEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重试次数: 的本地化字符串。
        /// </summary>
        public static string RetryCount {
            get {
                return ResourceManager.GetString("RetryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回成功验证: 的本地化字符串。
        /// </summary>
        public static string ReturnSuccessValidation {
            get {
                return ResourceManager.GetString("ReturnSuccessValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 根目录 的本地化字符串。
        /// </summary>
        public static string RootDirectory {
            get {
                return ResourceManager.GetString("RootDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采样频率: 的本地化字符串。
        /// </summary>
        public static string SamplingFrequency {
            get {
                return ResourceManager.GetString("SamplingFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存失败 的本地化字符串。
        /// </summary>
        public static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存设置 的本地化字符串。
        /// </summary>
        public static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功 的本地化字符串。
        /// </summary>
        public static string SaveSuccessful {
            get {
                return ResourceManager.GetString("SaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扫描数量 的本地化字符串。
        /// </summary>
        public static string ScanCount {
            get {
                return ResourceManager.GetString("ScanCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扫码间隔: 的本地化字符串。
        /// </summary>
        public static string ScanInterval {
            get {
                return ResourceManager.GetString("ScanInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 天之前的扫码图片 的本地化字符串。
        /// </summary>
        public static string ScannedImageDaysAgo {
            get {
                return ResourceManager.GetString("ScannedImageDaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扫码图片 的本地化字符串。
        /// </summary>
        public static string ScannedImages {
            get {
                return ResourceManager.GetString("ScannedImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扫码相机 的本地化字符串。
        /// </summary>
        public static string ScannerCamera {
            get {
                return ResourceManager.GetString("ScannerCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扫码图 的本地化字符串。
        /// </summary>
        public static string ScannerImage {
            get {
                return ResourceManager.GetString("ScannerImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扫码时间: 的本地化字符串。
        /// </summary>
        public static string ScanTime {
            get {
                return ResourceManager.GetString("ScanTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查找 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用的Api接口: 的本地化字符串。
        /// </summary>
        public static string SelectedApi {
            get {
                return ResourceManager.GetString("SelectedApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送延迟: 的本地化字符串。
        /// </summary>
        public static string SendDelay {
            get {
                return ResourceManager.GetString("SendDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送内容: 的本地化字符串。
        /// </summary>
        public static string SentContent {
            get {
                return ResourceManager.GetString("SentContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分隔符 的本地化字符串。
        /// </summary>
        public static string Separator {
            get {
                return ResourceManager.GetString("Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口连接 的本地化字符串。
        /// </summary>
        public static string SerialPortConnection {
            get {
                return ResourceManager.GetString("SerialPortConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口名: 的本地化字符串。
        /// </summary>
        public static string SerialPortName {
            get {
                return ResourceManager.GetString("SerialPortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单码扫描间隔时间: 的本地化字符串。
        /// </summary>
        public static string SingleCodeScanInterval {
            get {
                return ResourceManager.GetString("SingleCodeScanInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 智能相机 的本地化字符串。
        /// </summary>
        public static string SmartCamera {
            get {
                return ResourceManager.GetString("SmartCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 稳定精度: 的本地化字符串。
        /// </summary>
        public static string StabilityAccuracy {
            get {
                return ResourceManager.GetString("StabilityAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 稳定个数: 的本地化字符串。
        /// </summary>
        public static string StabilityCount {
            get {
                return ResourceManager.GetString("StabilityCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常规连接参数: 的本地化字符串。
        /// </summary>
        public static string StandardConnectionParameters {
            get {
                return ResourceManager.GetString("StandardConnectionParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始 的本地化字符串。
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开头字符: 的本地化字符串。
        /// </summary>
        public static string StartCharacter {
            get {
                return ResourceManager.GetString("StartCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小数起始位置: 的本地化字符串。
        /// </summary>
        public static string StartPositionOfDecimal {
            get {
                return ResourceManager.GetString("StartPositionOfDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 整数起始位置: 的本地化字符串。
        /// </summary>
        public static string StartPositionOfInteger {
            get {
                return ResourceManager.GetString("StartPositionOfInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 静态称重 的本地化字符串。
        /// </summary>
        public static string StaticWeighing {
            get {
                return ResourceManager.GetString("StaticWeighing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机 的本地化字符串。
        /// </summary>
        public static string StatusBarCamera {
            get {
                return ResourceManager.GetString("StatusBarCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常 的本地化字符串。
        /// </summary>
        public static string StatusBarException {
            get {
                return ResourceManager.GetString("StatusBarException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内存: 的本地化字符串。
        /// </summary>
        public static string StatusBarMemory {
            get {
                return ResourceManager.GetString("StatusBarMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口 的本地化字符串。
        /// </summary>
        public static string StatusBarSerialPort {
            get {
                return ResourceManager.GetString("StatusBarSerialPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 监控 的本地化字符串。
        /// </summary>
        public static string StatusBarStatus {
            get {
                return ResourceManager.GetString("StatusBarStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温度: 的本地化字符串。
        /// </summary>
        public static string StatusBarTemperature {
            get {
                return ResourceManager.GetString("StatusBarTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止位: 的本地化字符串。
        /// </summary>
        public static string StopBits {
            get {
                return ResourceManager.GetString("StopBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子路径: 的本地化字符串。
        /// </summary>
        public static string SubDirectory {
            get {
                return ResourceManager.GetString("SubDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功音频: 的本地化字符串。
        /// </summary>
        public static string SuccessAudio {
            get {
                return ResourceManager.GetString("SuccessAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传状态 的本地化字符串。
        /// </summary>
        public static string TableHeaderAPIResponseStatus {
            get {
                return ResourceManager.GetString("TableHeaderAPIResponseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条码 的本地化字符串。
        /// </summary>
        public static string TableHeaderBarCode {
            get {
                return ResourceManager.GetString("TableHeaderBarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片 的本地化字符串。
        /// </summary>
        public static string TableHeaderBarcodeImage {
            get {
                return ResourceManager.GetString("TableHeaderBarcodeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机品牌 的本地化字符串。
        /// </summary>
        public static string TableHeaderCameraBrand {
            get {
                return ResourceManager.GetString("TableHeaderCameraBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机型号 的本地化字符串。
        /// </summary>
        public static string TableHeaderCameraModel {
            get {
                return ResourceManager.GetString("TableHeaderCameraModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机名称 的本地化字符串。
        /// </summary>
        public static string TableHeaderCameraName {
            get {
                return ResourceManager.GetString("TableHeaderCameraName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机类型 的本地化字符串。
        /// </summary>
        public static string TableHeaderCameraType {
            get {
                return ResourceManager.GetString("TableHeaderCameraType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 延迟触发时间 的本地化字符串。
        /// </summary>
        public static string TableHeaderDelayTriggerTime {
            get {
                return ResourceManager.GetString("TableHeaderDelayTriggerTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否开启实时图像 的本地化字符串。
        /// </summary>
        public static string TableHeaderEnableRealTimeImage {
            get {
                return ResourceManager.GetString("TableHeaderEnableRealTimeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高度 的本地化字符串。
        /// </summary>
        public static string TableHeaderHeight {
            get {
                return ResourceManager.GetString("TableHeaderHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片类型 的本地化字符串。
        /// </summary>
        public static string TableHeaderImageType {
            get {
                return ResourceManager.GetString("TableHeaderImageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP地址 的本地化字符串。
        /// </summary>
        public static string TableHeaderIPAddress {
            get {
                return ResourceManager.GetString("TableHeaderIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 长度 的本地化字符串。
        /// </summary>
        public static string TableHeaderLength {
            get {
                return ResourceManager.GetString("TableHeaderLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大长度 的本地化字符串。
        /// </summary>
        public static string TableHeaderMaximumLength {
            get {
                return ResourceManager.GetString("TableHeaderMaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大同步时间 的本地化字符串。
        /// </summary>
        public static string TableHeaderMaximumSynchronizationTime {
            get {
                return ResourceManager.GetString("TableHeaderMaximumSynchronizationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测量模式 的本地化字符串。
        /// </summary>
        public static string TableHeaderMeasurementMode {
            get {
                return ResourceManager.GetString("TableHeaderMeasurementMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小长度 的本地化字符串。
        /// </summary>
        public static string TableHeaderMinimumLength {
            get {
                return ResourceManager.GetString("TableHeaderMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小同步时间 的本地化字符串。
        /// </summary>
        public static string TableHeaderMinimumSynchronizationTime {
            get {
                return ResourceManager.GetString("TableHeaderMinimumSynchronizationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string TableHeaderOperation {
            get {
                return ResourceManager.GetString("TableHeaderOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全景图片 的本地化字符串。
        /// </summary>
        public static string TableHeaderPanoramicImage {
            get {
                return ResourceManager.GetString("TableHeaderPanoramicImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求内容 的本地化字符串。
        /// </summary>
        public static string TableHeaderRequestContent {
            get {
                return ResourceManager.GetString("TableHeaderRequestContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 响应内容 的本地化字符串。
        /// </summary>
        public static string TableHeaderResponseContent {
            get {
                return ResourceManager.GetString("TableHeaderResponseContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扫描时间 的本地化字符串。
        /// </summary>
        public static string TableHeaderScanTime {
            get {
                return ResourceManager.GetString("TableHeaderScanTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机序列号 的本地化字符串。
        /// </summary>
        public static string TableHeaderSerialNumber {
            get {
                return ResourceManager.GetString("TableHeaderSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间戳Guid 的本地化字符串。
        /// </summary>
        public static string TableHeaderTimestampGuid {
            get {
                return ResourceManager.GetString("TableHeaderTimestampGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触发模式 的本地化字符串。
        /// </summary>
        public static string TableHeaderTriggerMode {
            get {
                return ResourceManager.GetString("TableHeaderTriggerMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本号 的本地化字符串。
        /// </summary>
        public static string TableHeaderVersionNumber {
            get {
                return ResourceManager.GetString("TableHeaderVersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 体积 的本地化字符串。
        /// </summary>
        public static string TableHeaderVolume {
            get {
                return ResourceManager.GetString("TableHeaderVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重量 的本地化字符串。
        /// </summary>
        public static string TableHeaderWeight {
            get {
                return ResourceManager.GetString("TableHeaderWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宽度 的本地化字符串。
        /// </summary>
        public static string TableHeaderWidth {
            get {
                return ResourceManager.GetString("TableHeaderWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tcp连接 的本地化字符串。
        /// </summary>
        public static string TCPConnection {
            get {
                return ResourceManager.GetString("TCPConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试图片路径: 的本地化字符串。
        /// </summary>
        public static string TestImagePath {
            get {
                return ResourceManager.GetString("TestImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超时时间: 的本地化字符串。
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间戳Guid: 的本地化字符串。
        /// </summary>
        public static string TimestampGuid {
            get {
                return ResourceManager.GetString("TimestampGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左上角 的本地化字符串。
        /// </summary>
        public static string TopLeftCorner {
            get {
                return ResourceManager.GetString("TopLeftCorner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右上角 的本地化字符串。
        /// </summary>
        public static string TopRightCorner {
            get {
                return ResourceManager.GetString("TopRightCorner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总内存: 的本地化字符串。
        /// </summary>
        public static string TotalMemory {
            get {
                return ResourceManager.GetString("TotalMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测量触发模式: 的本地化字符串。
        /// </summary>
        public static string TriggerMode {
            get {
                return ResourceManager.GetString("TriggerMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触发位置: 的本地化字符串。
        /// </summary>
        public static string TriggerPosition {
            get {
                return ResourceManager.GetString("TriggerPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解绑 的本地化字符串。
        /// </summary>
        public static string Unbind {
            get {
                return ResourceManager.GetString("Unbind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传数量 的本地化字符串。
        /// </summary>
        public static string UploadCount {
            get {
                return ResourceManager.GetString("UploadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Usb连接 的本地化字符串。
        /// </summary>
        public static string USBConnection {
            get {
                return ResourceManager.GetString("USBConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名: 的本地化字符串。
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试 的本地化字符串。
        /// </summary>
        public static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 追加重量的值: 的本地化字符串。
        /// </summary>
        public static string ValueOfAdditionalWeight {
            get {
                return ResourceManager.GetString("ValueOfAdditionalWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 固定重量的值: 的本地化字符串。
        /// </summary>
        public static string ValueOfFixedWeight {
            get {
                return ResourceManager.GetString("ValueOfFixedWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录像相机/安防相机 的本地化字符串。
        /// </summary>
        public static string VideoCameraSecurityCamera {
            get {
                return ResourceManager.GetString("VideoCameraSecurityCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看图像 的本地化字符串。
        /// </summary>
        public static string ViewImage {
            get {
                return ResourceManager.GetString("ViewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看全景图 的本地化字符串。
        /// </summary>
        public static string ViewPanoramaImage {
            get {
                return ResourceManager.GetString("ViewPanoramaImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 体积: 的本地化字符串。
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 体积相机 的本地化字符串。
        /// </summary>
        public static string VolumeCamera {
            get {
                return ResourceManager.GetString("VolumeCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 体积图 的本地化字符串。
        /// </summary>
        public static string VolumeImage {
            get {
                return ResourceManager.GetString("VolumeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 体积设置 的本地化字符串。
        /// </summary>
        public static string VolumeSettings {
            get {
                return ResourceManager.GetString("VolumeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 体积单位: 的本地化字符串。
        /// </summary>
        public static string VolumeUnit {
            get {
                return ResourceManager.GetString("VolumeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水印: 的本地化字符串。
        /// </summary>
        public static string Watermark {
            get {
                return ResourceManager.GetString("Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水印颜色: 的本地化字符串。
        /// </summary>
        public static string WatermarkColor {
            get {
                return ResourceManager.GetString("WatermarkColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水印内容: 的本地化字符串。
        /// </summary>
        public static string WatermarkContent {
            get {
                return ResourceManager.GetString("WatermarkContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水印位置: 的本地化字符串。
        /// </summary>
        public static string WatermarkPosition {
            get {
                return ResourceManager.GetString("WatermarkPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水印大小: 的本地化字符串。
        /// </summary>
        public static string WatermarkSize {
            get {
                return ResourceManager.GetString("WatermarkSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 称重模式: 的本地化字符串。
        /// </summary>
        public static string WeighingMode {
            get {
                return ResourceManager.GetString("WeighingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重量: 的本地化字符串。
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重量转换率: 的本地化字符串。
        /// </summary>
        public static string WeightConversionRate {
            get {
                return ResourceManager.GetString("WeightConversionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重量坐标: 的本地化字符串。
        /// </summary>
        public static string WeightPoints {
            get {
                return ResourceManager.GetString("WeightPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重量设置参数: 的本地化字符串。
        /// </summary>
        public static string WeightSettingParameters {
            get {
                return ResourceManager.GetString("WeightSettingParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 称重设置 的本地化字符串。
        /// </summary>
        public static string WeightSettings {
            get {
                return ResourceManager.GetString("WeightSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宽度: 的本地化字符串。
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年份 的本地化字符串。
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不是正确的正则表达式 的本地化字符串。
        /// </summary>
        public static string 不是正确的正则表达式 {
            get {
                return ResourceManager.GetString("不是正确的正则表达式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位图文件 的本地化字符串。
        /// </summary>
        public static string 位图文件 {
            get {
                return ResourceManager.GetString("位图文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 体积相机配置 的本地化字符串。
        /// </summary>
        public static string 体积相机配置 {
            get {
                return ResourceManager.GetString("体积相机配置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 体积设置相关 的本地化字符串。
        /// </summary>
        public static string 体积设置相关 {
            get {
                return ResourceManager.GetString("体积设置相关", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全景相机配置 的本地化字符串。
        /// </summary>
        public static string 全景相机配置 {
            get {
                return ResourceManager.GetString("全景相机配置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容输入相关设置 的本地化字符串。
        /// </summary>
        public static string 内容输入相关设置 {
            get {
                return ResourceManager.GetString("内容输入相关设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换Api接口失败! 的本地化字符串。
        /// </summary>
        public static string 切换Api接口失败 {
            get {
                return ResourceManager.GetString("切换Api接口失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言设置失败 的本地化字符串。
        /// </summary>
        public static string 切换语言失败提示 {
            get {
                return ResourceManager.GetString("切换语言失败提示", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言设置成功,重启程序生效 的本地化字符串。
        /// </summary>
        public static string 切换语言成功提示 {
            get {
                return ResourceManager.GetString("切换语言成功提示", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列表中没有数据 的本地化字符串。
        /// </summary>
        public static string 列表中没有数据 {
            get {
                return ResourceManager.GetString("列表中没有数据", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除失败 的本地化字符串。
        /// </summary>
        public static string 删除失败 {
            get {
                return ResourceManager.GetString("删除失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功 的本地化字符串。
        /// </summary>
        public static string 删除成功 {
            get {
                return ResourceManager.GetString("删除成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载磅秤设置失败 的本地化字符串。
        /// </summary>
        public static string 加载磅秤设置失败 {
            get {
                return ResourceManager.GetString("加载磅秤设置失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载设置失败 的本地化字符串。
        /// </summary>
        public static string 加载设置失败 {
            get {
                return ResourceManager.GetString("加载设置失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载过滤设置失败 的本地化字符串。
        /// </summary>
        public static string 加载过滤设置失败 {
            get {
                return ResourceManager.GetString("加载过滤设置失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动态称异常 的本地化字符串。
        /// </summary>
        public static string 动态称异常 {
            get {
                return ResourceManager.GetString("动态称异常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动态称连接成功 的本地化字符串。
        /// </summary>
        public static string 动态称连接成功 {
            get {
                return ResourceManager.GetString("动态称连接成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现所有相机 的本地化字符串。
        /// </summary>
        public static string 发现所有相机 {
            get {
                return ResourceManager.GetString("发现所有相机", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送失败 的本地化字符串。
        /// </summary>
        public static string 发送失败 {
            get {
                return ResourceManager.GetString("发送失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送成功 的本地化字符串。
        /// </summary>
        public static string 发送成功 {
            get {
                return ResourceManager.GetString("发送成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片不存在 的本地化字符串。
        /// </summary>
        public static string 图片不存在 {
            get {
                return ResourceManager.GetString("图片不存在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片保存异常 的本地化字符串。
        /// </summary>
        public static string 图片保存异常 {
            get {
                return ResourceManager.GetString("图片保存异常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片命名解析错误,未找到模板内容! 的本地化字符串。
        /// </summary>
        public static string 图片命名解析错误_未找到模板内容 {
            get {
                return ResourceManager.GetString("图片命名解析错误,未找到模板内容", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 声音文件 的本地化字符串。
        /// </summary>
        public static string 声音文件 {
            get {
                return ResourceManager.GetString("声音文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外部输入异常 的本地化字符串。
        /// </summary>
        public static string 外部输入异常 {
            get {
                return ResourceManager.GetString("外部输入异常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存图异常 的本地化字符串。
        /// </summary>
        public static string 存图异常 {
            get {
                return ResourceManager.GetString("存图异常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存图相关设置 的本地化字符串。
        /// </summary>
        public static string 存图相关设置 {
            get {
                return ResourceManager.GetString("存图相关设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存图路径解析错误,未找到模板内容! 的本地化字符串。
        /// </summary>
        public static string 存图路径解析错误_未找到模板内容 {
            get {
                return ResourceManager.GetString("存图路径解析错误,未找到模板内容", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已重新枚举相机 的本地化字符串。
        /// </summary>
        public static string 已重新枚举相机 {
            get {
                return ResourceManager.GetString("已重新枚举相机", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须先停止运行再设置条码过滤才能生效 的本地化字符串。
        /// </summary>
        public static string 必须先停止运行再设置条码过滤才能生效 {
            get {
                return ResourceManager.GetString("必须先停止运行再设置条码过滤才能生效", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扫码相机配置 的本地化字符串。
        /// </summary>
        public static string 扫码相机配置 {
            get {
                return ResourceManager.GetString("扫码相机配置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据信息管理 的本地化字符串。
        /// </summary>
        public static string 数据信息管理 {
            get {
                return ResourceManager.GetString("数据信息管理", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条码过滤相关设置 的本地化字符串。
        /// </summary>
        public static string 条码过滤相关设置 {
            get {
                return ResourceManager.GetString("条码过滤相关设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试水印 的本地化字符串。
        /// </summary>
        public static string 测试水印 {
            get {
                return ResourceManager.GetString("测试水印", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加失败 的本地化字符串。
        /// </summary>
        public static string 添加失败 {
            get {
                return ResourceManager.GetString("添加失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加成功 的本地化字符串。
        /// </summary>
        public static string 添加成功 {
            get {
                return ResourceManager.GetString("添加成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机检索成功 的本地化字符串。
        /// </summary>
        public static string 相机检索成功 {
            get {
                return ResourceManager.GetString("相机检索成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机管理配置 的本地化字符串。
        /// </summary>
        public static string 相机管理配置 {
            get {
                return ResourceManager.GetString("相机管理配置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 磅秤和称重设置相关 的本地化字符串。
        /// </summary>
        public static string 磅秤和称重设置相关 {
            get {
                return ResourceManager.GetString("磅秤和称重设置相关", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结果输出异常 的本地化字符串。
        /// </summary>
        public static string 结果输出异常 {
            get {
                return ResourceManager.GetString("结果输出异常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结果输出相关设置 的本地化字符串。
        /// </summary>
        public static string 结果输出相关设置 {
            get {
                return ResourceManager.GetString("结果输出相关设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备运行中则不能解绑或者绑定! 的本地化字符串。
        /// </summary>
        public static string 设备运行中则不能解绑或者绑定 {
            get {
                return ResourceManager.GetString("设备运行中则不能解绑或者绑定", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置参数失败! 的本地化字符串。
        /// </summary>
        public static string 设置参数失败 {
            get {
                return ResourceManager.GetString("设置参数失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择声音文件 的本地化字符串。
        /// </summary>
        public static string 请选择声音文件 {
            get {
                return ResourceManager.GetString("请选择声音文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择需要打开的图片 的本地化字符串。
        /// </summary>
        public static string 请选择需要打开的图片 {
            get {
                return ResourceManager.GetString("请选择需要打开的图片", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出数据格式错误,未找到模板内容 的本地化字符串。
        /// </summary>
        public static string 输出数据格式错误_未找到模板内容 {
            get {
                return ResourceManager.GetString("输出数据格式错误,未找到模板内容", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行日志、设备日志、通讯日志管理 的本地化字符串。
        /// </summary>
        public static string 运行日志_设备日志_通讯日志管理 {
            get {
                return ResourceManager.GetString("运行日志\\设备日志\\通讯日志管理", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 释放缓存/空间的方案 的本地化字符串。
        /// </summary>
        public static string 释放缓存_空间的方案 {
            get {
                return ResourceManager.GetString("释放缓存/空间的方案", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 释放设备异常 的本地化字符串。
        /// </summary>
        public static string 释放设备异常 {
            get {
                return ResourceManager.GetString("释放设备异常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 静态称异常 的本地化字符串。
        /// </summary>
        public static string 静态称异常 {
            get {
                return ResourceManager.GetString("静态称异常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 静态称连接成功 的本地化字符串。
        /// </summary>
        public static string 静态称连接成功 {
            get {
                return ResourceManager.GetString("静态称连接成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证不通过 的本地化字符串。
        /// </summary>
        public static string 验证不通过 {
            get {
                return ResourceManager.GetString("验证不通过", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证通过 的本地化字符串。
        /// </summary>
        public static string 验证通过 {
            get {
                return ResourceManager.GetString("验证通过", resourceCulture);
            }
        }
    }
}
