<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64;x86</Platforms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Sound\fail.wav" />
    <None Remove="Sound\success.wav" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Sound\fail.wav" />
    <EmbeddedResource Include="Sound\success.wav" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentFTP" />
    <PackageReference Include="HidSharpCore" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="NLog" />
    <PackageReference Include="NPOI" />
    <PackageReference Include="RawInput.Sharp" />
    <PackageReference Include="S7netplus" />
    <PackageReference Include="System.IO.Ports" />
    <PackageReference Include="System.Speech" />
    <PackageReference Include="TouchSocket" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Machine\" />
    <Folder Include="Speech\Container\" />
  </ItemGroup>

</Project>
