<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Sound\fail.wav" />
    <None Remove="Sound\success.wav" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Sound\fail.wav" />
    <EmbeddedResource Include="Sound\success.wav" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NPOI" Version="2.6.0" />
    <PackageReference Include="System.IO.Ports" Version="7.0.0" />
    <PackageReference Include="System.Speech" Version="7.0.0" />
  </ItemGroup>

</Project>
