<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EFCore.BulkExtensions" />
    <PackageReference Include="LibreHardwareMonitorLib" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Common" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="NLog" />
    <PackageReference Include="NLog.Web.AspNetCore" />
    <PackageReference Include="Pitcher" />
    <PackageReference Include="Polly" />
    <PackageReference Include="Polly.Caching.Memory" />
    <PackageReference Include="MessagePack" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="TouchSocket" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JayTom.Dws.Abstractions\JayTom.Dws.Abstractions.csproj" />
    <ProjectReference Include="..\JayTom.Dws.Application\JayTom.Dws.Application.csproj" />
    <ProjectReference Include="..\JayTom.Dws.Models\JayTom.Dws.Models.csproj" />
    <ProjectReference Include="..\JayTom.Dws.Domain\JayTom.Dws.Domain.csproj" />
  </ItemGroup>

</Project>
