<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="BaiduOcr\**" />
    <EmbeddedResource Remove="BaiduOcr\**" />
    <None Remove="BaiduOcr\**" />
    <Page Remove="BaiduOcr\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="BaiDuOcr.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Ini" Version="7.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Drawing.Common" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="OpenCvSharp">
      <HintPath>C:\Users\77051\Desktop\ExpressBillCSharpSDK_V2.1.1\ExpressBillCSharpSDK\ExpressBillCSharpSDK\bin\net7.0-windows\OpenCvSharp.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="ExpressBill\Lib\Dll\ExpressBillApi.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\Dll\libcurl.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\Dll\libeay32.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\Dll\libiconv.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\Dll\libiomp5md.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\Dll\libzbar64-0.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\Dll\mkldnn.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\Dll\mklml.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\Dll\model-encrypt.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\Dll\ocrgve.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\Dll\onnxruntime.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\Dll\openblas.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\Dll\OpenCvSharpExtern.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\Dll\opencv_world410.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\Dll\paddle2onnx.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\Dll\paddle_inference.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\Dll\ssleay32.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\Dll\vka_license.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\license\license.ini">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\license\license.key">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\resource\alphabet_43_new.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\resource\alphabet_46.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\resource\class_conf.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\resource\configure.ini">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\resource\linedetect_23.paddle.encrypted">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\resource\linerecga.paddle.encrypted">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\resource\linerecgb.paddle.encrypted">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\resource\mainclassify.paddle.encrypted">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\resource\maindetect.paddle.encrypted">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\resource\ocr_model_v1_graph_waybill.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\resource\qrcode.paddle.encrypted">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\resource\quality.paddle.encrypted">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\resource\resource.tmp">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\resource\risk.paddle.encrypted">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\resource\table_10784_half">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\resource\table_10784_val">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\vc_redist\vc_redist.x64.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExpressBill\Lib\vc_redist\vc_redist.x86.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
