<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\Images\defaultImage.jpg" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\Images\defaultImage.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Blazor-ApexCharts" Version="2.2.1" />
    <PackageReference Include="MudBlazor" Version="6.14.0" />
    <PackageReference Include="MudBlazor.ThemeManager" Version="1.0.8" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NLog" Version="5.2.8" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="5.3.8" />
    <PackageReference Include="NPOI" Version="2.6.2" />
    <PackageReference Include="SkiaSharp.Views.Blazor" Version="2.88.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JayTom.Dws.Camera\JayTom.Dws.Camera.csproj" />
  </ItemGroup>

</Project>
