// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JayTom.Dws.CloudApiDbTest.Migrations
{
    [DbContext(typeof(Program.CloudApiContext1))]
    [Migration("20240122132129_Migrations")]
    partial class Migrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("JayTom.Dws.Data.Package.BarCodeInfoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Barcode");

                    b.Property<string>("CameraSerialNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CameraSerialNumber");

                    b.Property<long>("PackageId")
                        .HasColumnType("bigint")
                        .HasColumnName("PackageId");

                    b.Property<DateTime>("ScanTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ScanTime");

                    b.Property<int>("Source")
                        .HasColumnType("int")
                        .HasColumnName("Source");

                    b.HasKey("Id");

                    b.HasIndex("Barcode");

                    b.HasIndex("PackageId")
                        .IsUnique();

                    b.HasIndex("ScanTime")
                        .HasAnnotation("IndexSortOrder", "Descending");

                    b.ToTable("Data_BarCodeInfo", "dbo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.Package.CloudVideoUploadInfoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<long>("PackageId")
                        .HasColumnType("bigint")
                        .HasColumnName("PackageId");

                    b.Property<int>("PanoramaImageCount")
                        .HasColumnType("int")
                        .HasColumnName("PanoramaImageCount");

                    b.Property<string>("ResponseContent")
                        .HasColumnType("longtext")
                        .HasColumnName("ResponseContent");

                    b.Property<int>("ScanImageCount")
                        .HasColumnType("int")
                        .HasColumnName("ScanImageCount");

                    b.Property<string>("TargetAddress")
                        .HasColumnType("longtext")
                        .HasColumnName("TargetAddress");

                    b.Property<string>("UploadContent")
                        .HasColumnType("longtext")
                        .HasColumnName("UploadContent");

                    b.Property<int?>("UploadDuration")
                        .HasColumnType("int")
                        .HasColumnName("UploadDuration");

                    b.Property<DateTime?>("UploadTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UploadTime");

                    b.HasKey("Id");

                    b.ToTable("Data_CloudVideoUploadInfo", "dbo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.Package.DeviceInfoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("DeviceName");

                    b.Property<string>("MachineCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("MachineCode");

                    b.Property<string>("NodeName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("NodeName");

                    b.Property<long>("PackageId")
                        .HasColumnType("bigint")
                        .HasColumnName("PackageId");

                    b.HasKey("Id");

                    b.HasIndex("PackageId")
                        .IsUnique();

                    b.ToTable("Data_DeviceInfo", "dbo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.Package.ExitInfoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<long>("PackageId")
                        .HasColumnType("bigint")
                        .HasColumnName("PackageId");

                    b.Property<string>("PhysicalExit")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("PhysicalExit");

                    b.Property<long>("PhysicalExitId")
                        .HasColumnType("bigint")
                        .HasColumnName("PhysicalExitId");

                    b.Property<string>("TheoreticalExit")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TheoreticalExit");

                    b.HasKey("Id");

                    b.HasIndex("PackageId")
                        .IsUnique();

                    b.ToTable("Data_ExitInfo", "dbo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.Package.ImageInfoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<string>("CameraName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CameraName");

                    b.Property<string>("CameraSerialNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CameraSerialNumber");

                    b.Property<string>("CustomCameraName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CustomCameraName");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ImageUrl");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("LocalPath");

                    b.Property<long>("PackageId")
                        .HasColumnType("bigint")
                        .HasColumnName("PackageId");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.ToTable("Data_ImageInfo", "dbo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.Package.LogisticsInfoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<string>("LogisticsCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("LogisticsCode");

                    b.Property<string>("LogisticsName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("LogisticsName");

                    b.Property<long>("PackageId")
                        .HasColumnType("bigint")
                        .HasColumnName("PackageId");

                    b.HasKey("Id");

                    b.HasIndex("PackageId")
                        .IsUnique();

                    b.ToTable("Data_LogisticsInfo", "dbo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.Package.OcrDetailedInfoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Address");

                    b.Property<int>("InformationType")
                        .HasColumnType("int")
                        .HasColumnName("InfoType");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.Property<long>("OcrInfoId")
                        .HasColumnType("bigint")
                        .HasColumnName("OcrInfoId");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Phone");

                    b.HasKey("Id");

                    b.HasIndex("OcrInfoId");

                    b.ToTable("OcrDetailedInfoModel");
                });

            modelBuilder.Entity("JayTom.Dws.Data.Package.OcrInfoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<string>("CameraSerialNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CameraSerialNumber");

                    b.Property<long>("ElapsedMilliseconds")
                        .HasColumnType("bigint")
                        .HasColumnName("ElapsedMilliseconds");

                    b.Property<bool>("IsUseOcr")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsUseOcr");

                    b.Property<string>("OriginalContent")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("OriginalContent");

                    b.Property<long>("PackageId")
                        .HasColumnType("bigint")
                        .HasColumnName("PackageId");

                    b.Property<DateTime>("RecognizeTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("RecognizeTime");

                    b.Property<long>("SubmitTimestamp")
                        .HasColumnType("bigint")
                        .HasColumnName("SubmitTimestamp");

                    b.Property<string>("ThreeSegmentCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ThreeSegmentCode");

                    b.Property<string>("VirtualNumberLast4")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("VirtualNumberLast4");

                    b.HasKey("Id");

                    b.HasIndex("PackageId")
                        .IsUnique();

                    b.ToTable("Data_OcrInfo", "dbo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.Package.PackageInfoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<string>("Other")
                        .HasColumnType("longtext")
                        .HasColumnName("Other");

                    b.Property<DateTime>("PackageCreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("PackageCreateTime");

                    b.Property<long>("PackageTimestamped")
                        .HasColumnType("bigint")
                        .HasColumnName("PackageTimestamped");

                    b.HasKey("Id");

                    b.HasIndex("PackageCreateTime")
                        .HasAnnotation("IndexSortOrder", "Descending");

                    b.HasIndex("PackageTimestamped");

                    b.ToTable("Data_PackageInfo", "dbo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.Package.SortingInfoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<string>("ChecksumProtocolName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ChecksumProtocolName");

                    b.Property<string>("CommandTarget")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CommandTarget");

                    b.Property<int>("CommunicationMethod")
                        .HasColumnType("int")
                        .HasColumnName("CommunicationMethod");

                    b.Property<string>("ConnectionName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ConnectionName");

                    b.Property<bool>("IsAbnormalSorting")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsAbnormalSorting");

                    b.Property<bool>("IsCreatedByLowerMachine")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsCreatedByLowerMachine");

                    b.Property<bool>("IsSortingUsed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsSortingUsed");

                    b.Property<string>("PackageCreationInstruction")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("PackageCreationInstruction");

                    b.Property<long>("PackageId")
                        .HasColumnType("bigint")
                        .HasColumnName("PackageId");

                    b.Property<string>("ReceivedInstruction")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ReceivedInstruction");

                    b.Property<DateTime>("ReceivedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ReceivedTime");

                    b.Property<DateTime>("SendTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("SendTime");

                    b.Property<string>("SentInstruction")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("SentInstruction");

                    b.Property<int>("SortingMode")
                        .HasColumnType("int")
                        .HasColumnName("SortingMode");

                    b.HasKey("Id");

                    b.HasIndex("PackageId")
                        .IsUnique();

                    b.ToTable("Data_SortingInfo", "dbo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.Package.UploadInfoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<int>("ApiExceptionType")
                        .HasColumnType("int")
                        .HasColumnName("ApiExceptionType");

                    b.Property<double>("DurationInSeconds")
                        .HasColumnType("double")
                        .HasColumnName("DurationInSeconds");

                    b.Property<string>("ExceptionMessage")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ExceptionMessage");

                    b.Property<string>("InterfaceParameters")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("InterfaceParameters");

                    b.Property<long>("PackageId")
                        .HasColumnType("bigint")
                        .HasColumnName("PackageId");

                    b.Property<string>("RequestContent")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("RequestContent");

                    b.Property<int>("RequestStatus")
                        .HasColumnType("int")
                        .HasColumnName("RequestStatus");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("RequestTime");

                    b.Property<string>("RequestUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("RequestUrl");

                    b.Property<string>("ResponseContent")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ResponseContent");

                    b.Property<DateTime>("ResponseTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ResponseTime");

                    b.HasKey("Id");

                    b.HasIndex("PackageId")
                        .IsUnique();

                    b.ToTable("Data_UploadInfo", "dbo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.Package.VolumeInfoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateTime");

                    b.Property<double>("FormattedHeight")
                        .HasColumnType("double")
                        .HasColumnName("FormattedHeight");

                    b.Property<double>("FormattedLength")
                        .HasColumnType("double")
                        .HasColumnName("FormattedLength");

                    b.Property<double>("FormattedVolume")
                        .HasColumnType("double")
                        .HasColumnName("FormattedVolume");

                    b.Property<double>("FormattedWidth")
                        .HasColumnType("double")
                        .HasColumnName("FormattedWidth");

                    b.Property<string>("OriginalText")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("OriginalText");

                    b.Property<long>("PackageId")
                        .HasColumnType("bigint")
                        .HasColumnName("PackageId");

                    b.Property<int>("SourceType")
                        .HasColumnType("int")
                        .HasColumnName("SourceType");

                    b.HasKey("Id");

                    b.HasIndex("PackageId")
                        .IsUnique();

                    b.ToTable("Data_VolumeInfo", "dbo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.Package.WeightInfoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateTime");

                    b.Property<double>("FormattedWeight")
                        .HasColumnType("double")
                        .HasColumnName("FormattedWeight");

                    b.Property<string>("OriginalText")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("OriginalText");

                    b.Property<long>("PackageId")
                        .HasColumnType("bigint")
                        .HasColumnName("PackageId");

                    b.Property<int>("SourceType")
                        .HasColumnType("int")
                        .HasColumnName("SourceType");

                    b.Property<int>("WeighingMode")
                        .HasColumnType("int")
                        .HasColumnName("WeighingMode");

                    b.HasKey("Id");

                    b.HasIndex("PackageId")
                        .IsUnique();

                    b.ToTable("Data_WeightInfo", "dbo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.Package.BarCodeInfoModel", b =>
                {
                    b.HasOne("JayTom.Dws.Data.Package.PackageInfoModel", "PackageInfo")
                        .WithOne("BarCodeInfo")
                        .HasForeignKey("JayTom.Dws.Data.Package.BarCodeInfoModel", "PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PackageInfo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.Package.CloudVideoUploadInfoModel", b =>
                {
                    b.HasOne("JayTom.Dws.Data.Package.PackageInfoModel", "PackageInfo")
                        .WithOne("CloudVideoUploadInfo")
                        .HasForeignKey("JayTom.Dws.Data.Package.CloudVideoUploadInfoModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PackageInfo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.Package.DeviceInfoModel", b =>
                {
                    b.HasOne("JayTom.Dws.Data.Package.PackageInfoModel", "PackageInfo")
                        .WithOne("DeviceInfo")
                        .HasForeignKey("JayTom.Dws.Data.Package.DeviceInfoModel", "PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PackageInfo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.Package.ExitInfoModel", b =>
                {
                    b.HasOne("JayTom.Dws.Data.Package.PackageInfoModel", "PackageInfo")
                        .WithOne("ExitInfo")
                        .HasForeignKey("JayTom.Dws.Data.Package.ExitInfoModel", "PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PackageInfo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.Package.ImageInfoModel", b =>
                {
                    b.HasOne("JayTom.Dws.Data.Package.PackageInfoModel", "PackageInfo")
                        .WithMany("ImageInfos")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PackageInfo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.Package.LogisticsInfoModel", b =>
                {
                    b.HasOne("JayTom.Dws.Data.Package.PackageInfoModel", "PackageInfo")
                        .WithOne("LogisticsInfo")
                        .HasForeignKey("JayTom.Dws.Data.Package.LogisticsInfoModel", "PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PackageInfo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.Package.OcrDetailedInfoModel", b =>
                {
                    b.HasOne("JayTom.Dws.Data.Package.OcrInfoModel", "OcrInfo")
                        .WithMany("OcrDetailedInfos")
                        .HasForeignKey("OcrInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OcrInfo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.Package.OcrInfoModel", b =>
                {
                    b.HasOne("JayTom.Dws.Data.Package.PackageInfoModel", "PackageInfo")
                        .WithOne("OcrInfo")
                        .HasForeignKey("JayTom.Dws.Data.Package.OcrInfoModel", "PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PackageInfo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.Package.SortingInfoModel", b =>
                {
                    b.HasOne("JayTom.Dws.Data.Package.PackageInfoModel", "PackageInfo")
                        .WithOne("SortingInfo")
                        .HasForeignKey("JayTom.Dws.Data.Package.SortingInfoModel", "PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PackageInfo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.Package.UploadInfoModel", b =>
                {
                    b.HasOne("JayTom.Dws.Data.Package.PackageInfoModel", "PackageInfo")
                        .WithOne("UploadInfo")
                        .HasForeignKey("JayTom.Dws.Data.Package.UploadInfoModel", "PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PackageInfo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.Package.VolumeInfoModel", b =>
                {
                    b.HasOne("JayTom.Dws.Data.Package.PackageInfoModel", "PackageInfo")
                        .WithOne("VolumeInfo")
                        .HasForeignKey("JayTom.Dws.Data.Package.VolumeInfoModel", "PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PackageInfo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.Package.WeightInfoModel", b =>
                {
                    b.HasOne("JayTom.Dws.Data.Package.PackageInfoModel", "PackageInfo")
                        .WithOne("WeightInfo")
                        .HasForeignKey("JayTom.Dws.Data.Package.WeightInfoModel", "PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PackageInfo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.Package.OcrInfoModel", b =>
                {
                    b.Navigation("OcrDetailedInfos");
                });

            modelBuilder.Entity("JayTom.Dws.Data.Package.PackageInfoModel", b =>
                {
                    b.Navigation("BarCodeInfo");

                    b.Navigation("CloudVideoUploadInfo");

                    b.Navigation("DeviceInfo");

                    b.Navigation("ExitInfo");

                    b.Navigation("ImageInfos");

                    b.Navigation("LogisticsInfo");

                    b.Navigation("OcrInfo");

                    b.Navigation("SortingInfo");

                    b.Navigation("UploadInfo");

                    b.Navigation("VolumeInfo");

                    b.Navigation("WeightInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
