// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LicenseDBTest.Migrations
{
    [DbContext(typeof(Program.LicenseApiContext1))]
    [Migration("20240112103233_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("JayTom.Dws.Data.License.LicenseApplicationInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ApplicationName");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateTime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Description");

                    b.Property<long?>("LicensePermissionTemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("LicensePermissionTemplateId");

                    b.Property<string>("ModifyIp")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ModifyIp");

                    b.Property<DateTime>("ModifyTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ModifyTime");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Remarks");

                    b.HasKey("Id");

                    b.HasIndex("LicensePermissionTemplateId")
                        .IsUnique();

                    b.ToTable("App_LicenseApplicationInfo", "dbo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.License.LicenseClientBindingInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateTime");

                    b.Property<DateTime>("FirstActivatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("FirstActivatedDate");

                    b.Property<DateTime>("LastVerifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("LastVerifiedDate");

                    b.Property<string>("LicenseCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("LicenseCode");

                    b.Property<long>("LicenseCodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("LicenseCodeId");

                    b.Property<string>("MachineCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("MachineCode");

                    b.Property<string>("ModifyIp")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ModifyIp");

                    b.Property<DateTime>("ModifyTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ModifyTime");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Remarks");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("LicenseCodeId");

                    b.ToTable("Code_LicenseClientBindingInfo", "dbo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.License.LicenseCodeInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<int>("ActivatedClientCount")
                        .HasColumnType("int")
                        .HasColumnName("ActivatedClientCount");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ClientName");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateTime");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ExpirationDate");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsAvailable");

                    b.Property<string>("LicenseCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("LicenseCode");

                    b.Property<long>("LicensePermissionTemplateInfoId")
                        .HasColumnType("bigint")
                        .HasColumnName("LicensePermissionTemplateInfoId");

                    b.Property<int>("MaxClientCount")
                        .HasColumnType("int")
                        .HasColumnName("MaxClientCount");

                    b.Property<string>("ModifyIp")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ModifyIp");

                    b.Property<DateTime>("ModifyTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ModifyTime");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Remarks");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("LicensePermissionTemplateInfoId");

                    b.ToTable("Code_LicenseCodeInfo", "dbo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.License.LicenseFeatureInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateTime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Description");

                    b.Property<string>("FeatureGuid")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("FeatureGuid");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("FeatureName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<long>("LicenseApplicationInfoId")
                        .HasColumnType("bigint")
                        .HasColumnName("LicenseApplicationInfoId");

                    b.Property<string>("ModifyIp")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ModifyIp");

                    b.Property<DateTime>("ModifyTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ModifyTime");

                    b.Property<long>("Pid")
                        .HasColumnType("bigint")
                        .HasColumnName("Pid");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Remarks");

                    b.HasKey("Id");

                    b.HasIndex("LicenseApplicationInfoId");

                    b.ToTable("App_LicenseFeatureInfo", "dbo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.License.LicensePermissionTemplateInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CreateBy");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateTime");

                    b.Property<string>("ModifyIp")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ModifyIp");

                    b.Property<DateTime>("ModifyTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ModifyTime");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Remarks");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TemplateName");

                    b.HasKey("Id");

                    b.ToTable("App_LicensePermissionTemplateInfo", "dbo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.License.LicenseUserDetailsInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<string>("BusinessLicenseFilePath")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("BusinessLicenseFilePath");

                    b.Property<string>("CompanyAddress")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CompanyAddress");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CompanyName");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ContactEmail");

                    b.Property<string>("ContractFilePath")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ContractFilePath");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateTime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Description");

                    b.Property<string>("ModifyIp")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ModifyIp");

                    b.Property<DateTime>("ModifyTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ModifyTime");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Remarks");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Sys_LicenseUserDetailsInfo", "dbo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.License.LicenseUserInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateTime");

                    b.Property<string>("ModifyIp")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ModifyIp");

                    b.Property<DateTime>("ModifyTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ModifyTime");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("PassWord");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Phone");

                    b.Property<long>("Pid")
                        .HasColumnType("bigint")
                        .HasColumnName("Pid");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Remarks");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("Role");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("UserCode");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("UserName");

                    b.HasKey("Id");

                    b.ToTable("Sys_LicenseUserInfo", "dbo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.License.LicenseApplicationInfo", b =>
                {
                    b.HasOne("JayTom.Dws.Data.License.LicensePermissionTemplateInfo", "LicensePermissionTemplate")
                        .WithOne("LicenseApplicationInfo")
                        .HasForeignKey("JayTom.Dws.Data.License.LicenseApplicationInfo", "LicensePermissionTemplateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("LicensePermissionTemplate");
                });

            modelBuilder.Entity("JayTom.Dws.Data.License.LicenseClientBindingInfo", b =>
                {
                    b.HasOne("JayTom.Dws.Data.License.LicenseUserInfo", "UserInfo")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JayTom.Dws.Data.License.LicenseCodeInfo", "LicenseCodeInfo")
                        .WithMany("LicenseClientBindingInfo")
                        .HasForeignKey("LicenseCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LicenseCodeInfo");

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.License.LicenseCodeInfo", b =>
                {
                    b.HasOne("JayTom.Dws.Data.License.LicenseUserInfo", "UserInfo")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JayTom.Dws.Data.License.LicensePermissionTemplateInfo", "LicensePermissionTemplateInfo")
                        .WithMany("LicenseCodeInfos")
                        .HasForeignKey("LicensePermissionTemplateInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LicensePermissionTemplateInfo");

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.License.LicenseFeatureInfo", b =>
                {
                    b.HasOne("JayTom.Dws.Data.License.LicenseApplicationInfo", "LicenseApplicationInfo")
                        .WithMany("LicenseFeatureInfos")
                        .HasForeignKey("LicenseApplicationInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LicenseApplicationInfo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.License.LicenseUserDetailsInfo", b =>
                {
                    b.HasOne("JayTom.Dws.Data.License.LicenseUserInfo", "UserInfo")
                        .WithOne("UserDetailsInfo")
                        .HasForeignKey("JayTom.Dws.Data.License.LicenseUserDetailsInfo", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.License.LicenseApplicationInfo", b =>
                {
                    b.Navigation("LicenseFeatureInfos");
                });

            modelBuilder.Entity("JayTom.Dws.Data.License.LicenseCodeInfo", b =>
                {
                    b.Navigation("LicenseClientBindingInfo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.License.LicensePermissionTemplateInfo", b =>
                {
                    b.Navigation("LicenseApplicationInfo");

                    b.Navigation("LicenseCodeInfos");
                });

            modelBuilder.Entity("JayTom.Dws.Data.License.LicenseUserInfo", b =>
                {
                    b.Navigation("UserDetailsInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
