<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="appsettings.json" />
    <None Remove="Fonts\iconfont.ttf" />
    <None Remove="Fonts\更纱黑体 Mono SC Nerd.ttf" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DryIoc.Microsoft.DependencyInjection.Extension" Version="1.0.0.2" />
    <PackageReference Include="MaterialDesignThemes" Version="4.9.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="7.0.0" />
    <PackageReference Include="Prism.DryIoc" Version="8.1.97" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Converters\" />
    <Folder Include="Icons\" />
    <Folder Include="Sound\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JayTom.Dws.Data\JayTom.Dws.Data.csproj" />
    <ProjectReference Include="..\JayTom.Dws.Device\JayTom.Dws.Device.csproj" />
    <ProjectReference Include="..\JayTom.Dws.Domain\JayTom.Dws.Domain.csproj" />
    <ProjectReference Include="..\JayTom.Dws.Infrastructure\JayTom.Dws.Infrastructure.csproj" />
    <ProjectReference Include="..\JayTom.Dws.Interface\JayTom.Dws.Interface.csproj" />
    <ProjectReference Include="..\JayTom.Dws.Plugin\JayTom.Dws.Plugin.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Fonts\iconfont.ttf" />
    <Resource Include="Fonts\更纱黑体 Mono SC Nerd.ttf" />
  </ItemGroup>
  <Target Name="CopyDeviceLib" AfterTargets="AfterBuild">
    <ItemGroup>
      <DeviceLibFiles Include="$(SolutionDir)JayTom.Dws.Device\DeviceLib\*\*" />
    </ItemGroup>
    <Copy SourceFiles="@(DeviceLibFiles)" DestinationFolder="$(TargetDir)" />
  </Target>
</Project>
