<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>AnyCPU;x64;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="LogisticsBase64.dll" />
    <None Remove="turbojpeg.dll" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="LogisticsBase64.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="turbojpeg.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="LogisticsBaseCSharp">
      <HintPath>C:\Users\77051\Desktop\DWS_Demo_C#_Win64_V3.4.0.217968_20220907\lib\X64\LogisticsBaseCSharp.dll</HintPath>
    </Reference>
    <Reference Include="TurboJpegWrapper">
      <HintPath>C:\Users\77051\Desktop\DWS_Demo_C#_Win64_V3.4.0.217968_20220907\lib\X64\TurboJpegWrapper.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>