<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\JayTom.Dws.Camera\JayTom.Dws.Camera.csproj" />
    <ProjectReference Include="..\JayTom.Dws.License\JayTom.Dws.License.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="NetSDKCS">
      <HintPath>..\JayTom.Dws.Camera\Cameras\SecurityCamera\DaHuatech\Dll\NetSDKCS.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
