using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

const string PrintBaselineArgument = "--print-baseline";
const string WriteBaselineArgument = "--write-baseline";

var runtimeProjectDirectories = new[] {
    "JayTom.Dws.Camera",
    "JayTom.Dws.Client",
    "JayTom.Dws.Data",
    "JayTom.Dws.Domain",
    "JayTom.Dws.Infrastructure",
    "JayTom.Dws.Interface",
    "JayTom.Dws.License",
    "JayTom.Dws.Nvr",
    "JayTom.Dws.Ocr",
    "JayTom.Dws.Plugin",
    "JayTom.Dws.PluginInterface",
    "JayTom.Dws.Utils"
};

if (args.Length < 2) {
    Console.Error.WriteLine(
        "用法：CodeQualityGuard <工作区路径> <基线路径> [--print-baseline|--write-baseline]");
    return 2;
}

var workspacePath = Path.GetFullPath(args[0]);
var baselinePath = Path.GetFullPath(args[1]);
var printBaseline = args.Contains(PrintBaselineArgument, StringComparer.Ordinal);
var writeBaseline = args.Contains(WriteBaselineArgument, StringComparer.Ordinal);
var utf8 = new UTF8Encoding(false, true);
var chineseCharacter = new Regex(
    @"\p{IsCJKUnifiedIdeographs}",
    RegexOptions.Compiled | RegexOptions.CultureInvariant);
var forbiddenMojibake = new[] {
    "\uFFFD",
    "锟斤拷",
    "閿熸枻鎷",
    "銆",
    "鏁版嵁",
    "鐨勪",
    "涓€",
    "鍙樺寲"
};
var floatingPointViolations =
    new Dictionary<string, int>(StringComparer.Ordinal);
var documentationViolations =
    new Dictionary<string, int>(StringComparer.Ordinal);
var strictErrors = new List<string>();

foreach (var projectDirectory in runtimeProjectDirectories) {
    var absoluteProjectDirectory = Path.Combine(workspacePath, projectDirectory);
    foreach (var sourcePath in Directory.EnumerateFiles(
                 absoluteProjectDirectory,
                 "*.cs",
                 SearchOption.AllDirectories)) {
        if (IsGeneratedBuildFile(sourcePath)) {
            continue;
        }

        var relativePath = Path.GetRelativePath(workspacePath, sourcePath)
            .Replace('\\', '/');
        string source;
        try {
            source = utf8.GetString(File.ReadAllBytes(sourcePath));
        }
        catch (DecoderFallbackException exception) {
            strictErrors.Add(
                $"{relativePath}: 文件不是有效的 UTF-8 编码：{exception.Message}");
            continue;
        }

        foreach (var mojibake in forbiddenMojibake) {
            if (source.Contains(mojibake, StringComparison.Ordinal)) {
                strictErrors.Add(
                    $"{relativePath}: 检测到疑似中文乱码“{mojibake}”。");
            }
        }

        var syntaxTree = CSharpSyntaxTree.ParseText(
            source,
            new CSharpParseOptions(LanguageVersion.Latest),
            sourcePath,
            Encoding.UTF8);
        var root = syntaxTree.GetRoot();
        if (IsAutoGeneratedSource(root)) {
            continue;
        }

        DetectUtcUsage(root, relativePath, strictErrors);
        CountFloatingPointUsage(root, relativePath, floatingPointViolations);
        CountMissingChineseDocumentation(
            root,
            relativePath,
            chineseCharacter,
            documentationViolations);
    }
}

var currentBaseline = new GuardBaseline(
    floatingPointViolations,
    documentationViolations);
var baselineJson = JsonSerializer.Serialize(
    currentBaseline,
    new JsonSerializerOptions { WriteIndented = true });

if (printBaseline) {
    Console.WriteLine(baselineJson);
    return strictErrors.Count == 0 ? 0 : PrintErrors(strictErrors);
}

if (writeBaseline) {
    if (strictErrors.Count > 0) {
        return PrintErrors(strictErrors);
    }

    File.WriteAllText(baselinePath, baselineJson + Environment.NewLine, utf8);
    Console.WriteLine($"代码质量基线已更新：{baselinePath}");
    return 0;
}

if (!File.Exists(baselinePath)) {
    strictErrors.Add($"找不到代码质量基线：{baselinePath}");
}
else {
    try {
        var expectedBaseline = JsonSerializer.Deserialize<GuardBaseline>(
            File.ReadAllText(baselinePath, utf8),
            new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
        if (expectedBaseline is null) {
            strictErrors.Add($"代码质量基线内容为空：{baselinePath}");
        }
        else {
            CompareCounts(
                "浮点数",
                expectedBaseline.FloatingPoint,
                currentBaseline.FloatingPoint,
                strictErrors);
            CompareCounts(
                "缺少中文注释",
                expectedBaseline.MissingChineseDocumentation,
                currentBaseline.MissingChineseDocumentation,
                strictErrors);
        }
    }
    catch (Exception exception) when (
        exception is IOException or JsonException or DecoderFallbackException) {
        strictErrors.Add($"无法读取代码质量基线：{exception.Message}");
    }
}

if (strictErrors.Count > 0) {
    return PrintErrors(strictErrors);
}

Console.WriteLine(
    "代码质量守卫通过：未新增 UTC、浮点数、缺少中文注释或中文乱码。");
return 0;

static bool IsGeneratedBuildFile(string sourcePath) {
    return sourcePath.Contains(
               $"{Path.DirectorySeparatorChar}obj{Path.DirectorySeparatorChar}",
               StringComparison.OrdinalIgnoreCase) ||
           sourcePath.Contains(
               $"{Path.DirectorySeparatorChar}bin{Path.DirectorySeparatorChar}",
               StringComparison.OrdinalIgnoreCase);
}

static bool IsAutoGeneratedSource(SyntaxNode root) {
    return root.GetLeadingTrivia().ToFullString()
        .Contains("<auto-generated", StringComparison.OrdinalIgnoreCase);
}

static void DetectUtcUsage(
    SyntaxNode root,
    string relativePath,
    ICollection<string> errors) {
    foreach (var memberAccess in root.DescendantNodes()
                 .OfType<MemberAccessExpressionSyntax>()) {
        var expression = memberAccess.ToString();
        if (expression is "DateTime.UtcNow" or "DateTimeOffset.UtcNow" or
            "DateTimeKind.Utc" ||
            memberAccess.Name.Identifier.ValueText == "ToUniversalTime") {
            var line =
                memberAccess.GetLocation().GetLineSpan().StartLinePosition.Line + 1;
            errors.Add(
                $"{relativePath}({line}): 禁止使用 UTC 时间 API“{expression}”，请使用本地时间。");
        }
    }
}

static void CountFloatingPointUsage(
    SyntaxNode root,
    string relativePath,
    IDictionary<string, int> violations) {
    var count = root.DescendantNodes().Count(node => node switch {
        PredefinedTypeSyntax predefined when
            predefined.Keyword.IsKind(SyntaxKind.FloatKeyword) ||
            predefined.Keyword.IsKind(SyntaxKind.DoubleKeyword) => true,
        IdentifierNameSyntax identifier when
            identifier.Identifier.ValueText is "Half" or "Single" or "Double" => true,
        LiteralExpressionSyntax literal when
            literal.Token.Value is float or double => true,
        _ => false
    });

    if (count > 0) {
        violations[relativePath] = count;
    }
}

static void CountMissingChineseDocumentation(
    SyntaxNode root,
    string relativePath,
    Regex chineseCharacter,
    IDictionary<string, int> violations) {
    var count = 0;
    foreach (var node in root.DescendantNodes().Where(IsDocumentableDeclaration)) {
        var documentation = node.GetLeadingTrivia()
            .Select(trivia => trivia.GetStructure())
            .OfType<DocumentationCommentTriviaSyntax>()
            .FirstOrDefault();
        if (documentation is null ||
            !chineseCharacter.IsMatch(documentation.ToFullString())) {
            count++;
        }
    }

    if (count > 0) {
        violations[relativePath] = count;
    }
}

static bool IsDocumentableDeclaration(SyntaxNode node) {
    return node is BaseMethodDeclarationSyntax or LocalFunctionStatementSyntax or
        PropertyDeclarationSyntax or IndexerDeclarationSyntax or
        FieldDeclarationSyntax or EventFieldDeclarationSyntax or
        EnumMemberDeclarationSyntax;
}

static void CompareCounts(
    string category,
    IReadOnlyDictionary<string, int> expected,
    IReadOnlyDictionary<string, int> actual,
    ICollection<string> errors) {
    foreach (var (path, actualCount) in actual.OrderBy(
                 item => item.Key,
                 StringComparer.Ordinal)) {
        expected.TryGetValue(path, out var expectedCount);
        if (actualCount > expectedCount) {
            errors.Add(
                $"{path}: {category}数量由 {expectedCount} 增加到 {actualCount}；请修复新增违规。");
        }
    }
}

static int PrintErrors(IEnumerable<string> errors) {
    foreach (var error in errors.Distinct(StringComparer.Ordinal)) {
        Console.Error.WriteLine($"DWS0001: {error}");
    }

    return 1;
}

internal sealed record GuardBaseline(
    Dictionary<string, int> FloatingPoint,
    Dictionary<string, int> MissingChineseDocumentation);
