// <auto-generated />
using System;
using JayTom.Dws.VideoApiDbTest;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JayTom.Dws.VideoApiDbTest.Migrations
{
    [DbContext(typeof(VideoApiContextDB))]
    partial class VideoApiContextDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("JayTom.Dws.Data.LocalConf.CameraConfig.BarcodeScannerCameraConfigInfoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<string>("CameraConnectionParameters")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CameraConnectionParameters");

                    b.Property<int>("CameraType")
                        .HasColumnType("int")
                        .HasColumnName("CameraType");

                    b.Property<int>("ConnectionType")
                        .HasColumnType("int")
                        .HasColumnName("ConnectionType");

                    b.Property<string>("CustomName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CustomName");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("IpAddress");

                    b.Property<bool>("IsOcrSupported")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsOcrSupported");

                    b.Property<bool>("IsShowRealTimeImage")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsShowRealTimeImage");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("SerialNumber");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Version");

                    b.HasKey("Id");

                    b.ToTable("Conf_BarcodeScannerCameraConfigInfo", "dbo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.LocalConf.CloudConfig.NvrCameraBindingInfoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<int>("Channel")
                        .HasColumnType("int")
                        .HasColumnName("Channel");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("IpAddress");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Password");

                    b.Property<int>("Port")
                        .HasColumnType("int")
                        .HasColumnName("Port");

                    b.Property<long>("ScannerCameraConfigInfoModelId")
                        .HasColumnType("bigint")
                        .HasColumnName("ScannerCameraConfigInfoModelId");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.ToTable("Conf_NvrCameraBindingInfo", "dbo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.VideoApiData.VideoBarCodeInfoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Barcode");

                    b.Property<DateTime>("ScanTime")
                        .HasColumnType("datetime")
                        .HasColumnName("ScanTime");

                    b.Property<long>("TimestampedGuid")
                        .HasColumnType("bigint")
                        .HasColumnName("TimestampedGuid");

                    b.HasKey("Id");

                    b.ToTable("Data_VideoBarCodeInfo", "dbo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.VideoApiData.VideoNodeImageInfoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<string>("CameraName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CameraName");

                    b.Property<string>("CameraSerialNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CameraSerialNumber");

                    b.Property<int>("ImageType")
                        .HasColumnType("int")
                        .HasColumnName("ImageType");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Path");

                    b.Property<long>("ScanNodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("ScanNodeId");

                    b.HasKey("Id");

                    b.HasIndex("ScanNodeId");

                    b.ToTable("Data_VideoNodeImageInfo", "dbo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.VideoApiData.VideoScanNodeInfoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<long>("BarcodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("BarcodeId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.Property<DateTime>("ScanTime")
                        .HasColumnType("datetime")
                        .HasColumnName("ScanTime");

                    b.HasKey("Id");

                    b.HasIndex("BarcodeId");

                    b.ToTable("Data_VideoScanNodeInfo", "dbo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.VideoApiData.VideoNvrCameraBindingInfoModel", b =>
                {
                    b.HasBaseType("JayTom.Dws.Data.LocalConf.CloudConfig.NvrCameraBindingInfoModel");

                    b.Property<long>("ScanNodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("ScanNodeId");

                    b.HasIndex("ScanNodeId");

                    b.ToTable("Data_VideoNvrCameraBindingInfo", "dbo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.LocalConf.CloudConfig.NvrCameraBindingInfoModel", b =>
                {
                    b.HasOne("JayTom.Dws.Data.LocalConf.CameraConfig.BarcodeScannerCameraConfigInfoModel", "BarcodeScannerCameraConfigInfoModel")
                        .WithMany("NvrCameraBindingInfos")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BarcodeScannerCameraConfigInfoModel");
                });

            modelBuilder.Entity("JayTom.Dws.Data.VideoApiData.VideoNodeImageInfoModel", b =>
                {
                    b.HasOne("JayTom.Dws.Data.VideoApiData.VideoScanNodeInfoModel", "ScanNodeInfo")
                        .WithMany("VideoNodeImageInfos")
                        .HasForeignKey("ScanNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanNodeInfo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.VideoApiData.VideoScanNodeInfoModel", b =>
                {
                    b.HasOne("JayTom.Dws.Data.VideoApiData.VideoBarCodeInfoModel", "BarCodeInfo")
                        .WithMany("VideoScanNodeInfos")
                        .HasForeignKey("BarcodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BarCodeInfo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.VideoApiData.VideoNvrCameraBindingInfoModel", b =>
                {
                    b.HasOne("JayTom.Dws.Data.LocalConf.CloudConfig.NvrCameraBindingInfoModel", null)
                        .WithOne()
                        .HasForeignKey("JayTom.Dws.Data.VideoApiData.VideoNvrCameraBindingInfoModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JayTom.Dws.Data.VideoApiData.VideoScanNodeInfoModel", "ScanNodeInfo")
                        .WithMany("VideoNvrCameraBindingInfos")
                        .HasForeignKey("ScanNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanNodeInfo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.LocalConf.CameraConfig.BarcodeScannerCameraConfigInfoModel", b =>
                {
                    b.Navigation("NvrCameraBindingInfos");
                });

            modelBuilder.Entity("JayTom.Dws.Data.VideoApiData.VideoBarCodeInfoModel", b =>
                {
                    b.Navigation("VideoScanNodeInfos");
                });

            modelBuilder.Entity("JayTom.Dws.Data.VideoApiData.VideoScanNodeInfoModel", b =>
                {
                    b.Navigation("VideoNodeImageInfos");

                    b.Navigation("VideoNvrCameraBindingInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
