<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.IO.Ports" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JayTom.Dws.Data\JayTom.Dws.Data.csproj" />
    <ProjectReference Include="..\JayTom.Dws.Interface\JayTom.Dws.Interface.csproj" />
    <ProjectReference Include="..\JayTom.Dws.Plugin\JayTom.Dws.Plugin.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Repository\LocalConf\CloudConfig\" />
    <Folder Include="Repository\LocalConf\IpcNvrConfig\" />
    <Folder Include="Repository\VideoApi\" />
    <Folder Include="Service\VideoApi\" />
  </ItemGroup>

</Project>
