<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <UseNETFrameworkCompat>true</UseNETFrameworkCompat>
    <SupportedNETFrameworkVersions>4.0</SupportedNETFrameworkVersions>
    <Platforms>x64</Platforms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="BarCode64.dll" />
    <None Remove="blob64.dll" />
    <None Remove="CLAllSerial_MD_VC120_v3_0.dll" />
    <None Remove="CLProtocol_MD_VC120_v3_0.dll" />
    <None Remove="CLSerCOM.dll" />
    <None Remove="DataCode64.dll" />
    <None Remove="DeviceLib\PercipioLib\PercipioAppCentermt.dll" />
    <None Remove="encAlgVerify64.dll" />
    <None Remove="GCBase_MD_VC120_v3_0.dll" />
    <None Remove="GenApi_MD_VC120_v3_0.dll" />
    <None Remove="GenCP_MD_VC120_v3_0.dll" />
    <None Remove="GrayInstrument64.dll" />
    <None Remove="DeviceLib\HuaraytechLib\BarCode64.dll" />
    <None Remove="DeviceLib\HuaraytechLib\blob64.dll" />
    <None Remove="ImageConvert.dll" />
    <None Remove="libglog64.dll" />
    <None Remove="LibWndFindermd.dll" />
    <None Remove="log4cpp_MD_VC120_v3_0.dll" />
    <None Remove="Log_MD_VC120_v3_0.dll" />
    <None Remove="MathParser_MD_VC120_v3_0.dll" />
    <None Remove="Matting64.dll" />
    <None Remove="msvcp140.dll" />
    <None Remove="MVIDCodeReader.dll" />
    <None Remove="MVIDCodeReader.Net.dll" />
    <None Remove="MVlog4cppmd.dll" />
    <None Remove="MvpLoggermd.dll" />
    <None Remove="MVSDKmd.dll" />
    <None Remove="MvsFilters64.dll" />
    <None Remove="MvsSupport64.dll" />
    <None Remove="NetUtilitymd.dll" />
    <None Remove="NodeMapData_MD_VC120_v3_0.dll" />
    <None Remove="opencv_world300.dll" />
    <None Remove="OpenNI2.dll" />
    <None Remove="RulerFilter.dll" />
    <None Remove="SharpnessMeasure64.dll" />
    <None Remove="SocketCommunication.dll" />
    <None Remove="turbojpeg.dll" />
    <None Remove="ucrtbase.dll" />
    <None Remove="vcruntime140.dll" />
    <None Remove="Volume3DSdkmd.dll" />
    <None Remove="VRdll64.dll" />
    <None Remove="XmlParser_MD_VC120_v3_0.dll" />
  </ItemGroup>

  <ItemGroup>
    <ApplicationDefinition Include="DeviceLib\HuaraytechLib\BarCode64.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </ApplicationDefinition>
    <ApplicationDefinition Include="DeviceLib\HuaraytechLib\blob64.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </ApplicationDefinition>
    <Content Include="DeviceLib\HuaraytechLib\blob64.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="DeviceLib\HuaraytechLib\CLAllSerial_MD_VC120_v3_0.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="DeviceLib\HuaraytechLib\CLProtocol_MD_VC120_v3_0.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="DeviceLib\HuaraytechLib\CLSerCOM.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="DeviceLib\HuaraytechLib\DataCode64.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="DeviceLib\HuaraytechLib\encAlgVerify64.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="DeviceLib\HuaraytechLib\GCBase_MD_VC120_v3_0.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="DeviceLib\HuaraytechLib\GenApi_MD_VC120_v3_0.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="DeviceLib\HuaraytechLib\GenCP_MD_VC120_v3_0.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="DeviceLib\HuaraytechLib\GrayInstrument64.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="DeviceLib\HuaraytechLib\ImageConvert.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="DeviceLib\HuaraytechLib\libglog64.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="DeviceLib\HuaraytechLib\LibWndFindermd.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="DeviceLib\HuaraytechLib\log4cpp_MD_VC120_v3_0.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="DeviceLib\HuaraytechLib\LogisticsBase64.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="DeviceLib\HuaraytechLib\Log_MD_VC120_v3_0.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="DeviceLib\HuaraytechLib\MathParser_MD_VC120_v3_0.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="DeviceLib\HuaraytechLib\Matting64.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="DeviceLib\HuaraytechLib\msvcp140.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="DeviceLib\HuaraytechLib\MVlog4cppmd.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="DeviceLib\HuaraytechLib\MvpLoggermd.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="DeviceLib\HuaraytechLib\MVSDKmd.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="DeviceLib\HuaraytechLib\MvsFilters64.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="DeviceLib\HuaraytechLib\MvsSupport64.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="DeviceLib\HuaraytechLib\NetUtilitymd.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="DeviceLib\HuaraytechLib\NodeMapData_MD_VC120_v3_0.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="DeviceLib\HuaraytechLib\opencv_world300.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="DeviceLib\HuaraytechLib\OpenNI2.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="DeviceLib\HuaraytechLib\SharpnessMeasure64.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="DeviceLib\HuaraytechLib\SocketCommunication.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="DeviceLib\HuaraytechLib\turbojpeg.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="DeviceLib\HuaraytechLib\ucrtbase.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="DeviceLib\HuaraytechLib\vcruntime140.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="DeviceLib\HuaraytechLib\Volume3DSdkmd.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="DeviceLib\HuaraytechLib\VRdll64.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="DeviceLib\HuaraytechLib\XmlParser_MD_VC120_v3_0.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="DeviceLib\PercipioLib\PercipioAppCentermt.dll" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Drawing.Common" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Camera\IndustrialCamera\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="LogisticsBaseCSharp">
      <HintPath>C:\Users\77051\Desktop\DWS_Demo_C#2\bin\Release\x64\LogisticsBaseCSharp.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="TurboJpegWrapper">
      <HintPath>C:\Users\77051\Desktop\DWS_Demo_C#2\bin\Release\x64\TurboJpegWrapper.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>

  <!--<Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy /Y &quot;$(ProjectDir)\HuaraytechLib\*.*&quot; &quot;$(TargetDir)&quot;" />
  </Target>-->

</Project>
