<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Styles\" />
    <Folder Include="Service\" />
    <Folder Include="Models\" />
    <Folder Include="Fonts\" />
    <Folder Include="Converters\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DryIoc.Microsoft.DependencyInjection.Extension" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JayTom.Dws.PluginInterface\JayTom.Dws.PluginInterface.csproj" />
  </ItemGroup>

</Project>
