<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Cameras\VolumeCamera\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Drawing.Common" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MvCodeReaderSDK.Net">
      <HintPath>Cameras\SmartCamera\Hikvision\Dll\MvCodeReaderSDK.Net.dll</HintPath>
      <Private></Private>
    </Reference>
    <Reference Include="MVIDCodeReader.Net">
      <HintPath>Cameras\IndustrialCamera\Hikvision\Dll\MVIDCodeReader.Net.dll</HintPath>
      <Private></Private>
    </Reference>
    <Reference Include="NetSDKCS">
      <HintPath>Cameras\SecurityCamera\DaHuatech\Dll\NetSDKCS.dll</HintPath>
    </Reference>
    <Reference Include="ThridLibray">
      <HintPath>Cameras\SmartCamera\Irayple\Dll\ThridLibray.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="Cameras\IndustrialCamera\Hikvision\Dll\MVIDCodeReader.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Cameras\IndustrialCamera\Hikvision\Dll\MVIDCodeReader.Net.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Cameras\IndustrialCamera\Hikvision\Dll\RulerFilter.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Cameras\SecurityCamera\DaHuatech\Dll\avnetsdk.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Cameras\SecurityCamera\DaHuatech\Dll\dhconfigsdk.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Cameras\SecurityCamera\DaHuatech\Dll\dhnetsdk.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Cameras\SecurityCamera\DaHuatech\Dll\dhplay.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Cameras\SecurityCamera\DaHuatech\Dll\Infra.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Cameras\SecurityCamera\DaHuatech\Dll\IvsDrawer.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Cameras\SecurityCamera\DaHuatech\Dll\NetSDKCS.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Cameras\SecurityCamera\DaHuatech\Dll\NetSDKCS.pdb">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Cameras\SmartCamera\Hikvision\Dll\MvCodeReaderSDK.Net.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Cameras\SmartCamera\Hikvision\Dll\MvCodeReaderSDK.Net.XML">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Cameras\SmartCamera\Irayple\Dll\CLIDelegate.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Cameras\SmartCamera\Irayple\Dll\ThridLibray.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
