// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsoleApp5.Migrations
{
    [DbContext(typeof(Program.VideoApiContext1))]
    [Migration("20231211093837_MysqlMigrationName")]
    partial class MysqlMigrationName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("JayTom.Dws.Data.VideoApiData.VideoBarCodeInfoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Barcode");

                    b.Property<DateTime>("ScanTime")
                        .HasColumnType("datetime")
                        .HasColumnName("ScanTime");

                    b.Property<long>("TimestampedGuid")
                        .HasColumnType("bigint")
                        .HasColumnName("TimestampedGuid");

                    b.HasKey("Id");

                    b.ToTable("Data_VideoBarCodeInfo", "dbo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.VideoApiData.VideoNodeImageInfoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<string>("CameraName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CameraName");

                    b.Property<string>("CameraSerialNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CameraSerialNumber");

                    b.Property<int>("ImageType")
                        .HasColumnType("int")
                        .HasColumnName("ImageType");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Path");

                    b.Property<long>("ScanNodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("ScanNodeId");

                    b.HasKey("Id");

                    b.HasIndex("ScanNodeId");

                    b.ToTable("Data_VideoNodeImageInfo", "dbo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.VideoApiData.VideoScanNodeInfoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<long>("BarcodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("BarcodeId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.Property<DateTime>("ScanTime")
                        .HasColumnType("datetime")
                        .HasColumnName("ScanTime");

                    b.HasKey("Id");

                    b.HasIndex("BarcodeId");

                    b.ToTable("Data_VideoScanNodeInfo", "dbo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.VideoApiData.VideoNodeImageInfoModel", b =>
                {
                    b.HasOne("JayTom.Dws.Data.VideoApiData.VideoScanNodeInfoModel", "ScanNodeInfo")
                        .WithMany("VideoNodeImageInfos")
                        .HasForeignKey("ScanNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanNodeInfo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.VideoApiData.VideoScanNodeInfoModel", b =>
                {
                    b.HasOne("JayTom.Dws.Data.VideoApiData.VideoBarCodeInfoModel", "BarCodeInfo")
                        .WithMany("VideoScanNodeInfos")
                        .HasForeignKey("BarcodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BarCodeInfo");
                });

            modelBuilder.Entity("JayTom.Dws.Data.VideoApiData.VideoBarCodeInfoModel", b =>
                {
                    b.Navigation("VideoScanNodeInfos");
                });

            modelBuilder.Entity("JayTom.Dws.Data.VideoApiData.VideoScanNodeInfoModel", b =>
                {
                    b.Navigation("VideoNodeImageInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
